"""Contract tests for ApexPowers doctor checks."""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from types import ModuleType


ROOT = Path(__file__).resolve().parents[1]
DOCTOR = ROOT / ".codex" / "skills" / "apex-doctor" / "scripts" / "apex_doctor.py"


def load_doctor_module() -> ModuleType:
    """Load the doctor script constants for fixtures."""

    spec = importlib.util.spec_from_file_location("apex_doctor_under_test", DOCTOR)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load doctor script: {DOCTOR}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


DOCTOR_MODULE = load_doctor_module()


class ApexDoctorTests(unittest.TestCase):
    """Read-only health checks for ApexPowers installation surfaces."""

    def run_doctor(self, root: Path, codex_home: Path, claude_home: Path) -> subprocess.CompletedProcess[str]:
        """Run doctor with isolated agent homes."""

        return subprocess.run(
            [
                sys.executable,
                str(DOCTOR),
                str(root),
                "--codex-home",
                str(codex_home),
                "--claude-home",
                str(claude_home),
                "--json",
            ],
            text=True,
            encoding="utf-8",
            errors="replace",
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )

    def seed_core_skills(self, root: Path, missing: set[str] | None = None) -> None:
        """Create minimal core skill entrypoints."""

        missing = missing or set()
        for name in DOCTOR_MODULE.CORE_SKILLS:
            if name in missing:
                continue
            skill = root / ".codex" / "skills" / name
            skill.mkdir(parents=True, exist_ok=True)
            (skill / "SKILL.md").write_text(f"---\nname: {name}\n---\n", encoding="utf-8")

    def seed_agent_mirrors(self, root: Path) -> None:
        """Create one source agent and generated mirrors."""

        source = root / ".agents" / "developer.md"
        source.parent.mkdir(parents=True, exist_ok=True)
        source.write_text("---\nname: developer\n---\nDeveloper agent.\n", encoding="utf-8")
        for mirror in (root / ".codex" / "agents" / "developer.toml", root / ".claude" / "agents" / "developer.md"):
            mirror.parent.mkdir(parents=True, exist_ok=True)
            mirror.write_text(f"# {DOCTOR_MODULE.GENERATED_AGENT_MARKER}\n", encoding="utf-8")

    def seed_workflow(self, root: Path) -> None:
        """Create a minimal workflow state file."""

        workflow = root / "tasks" / "loops" / "workflow.md"
        workflow.parent.mkdir(parents=True, exist_ok=True)
        workflow.write_text(
            "\n".join(f"[apex-state:{state}]\nstate\n[/apex-state:{state}]" for state in DOCTOR_MODULE.WORKFLOW_STATES) + "\n",
            encoding="utf-8",
        )

    def seed_hook_install(self, root: Path, codex_home: Path, claude_home: Path) -> None:
        """Create minimal hook manifests, configs, and runtime files."""

        project_manifest = root / "tasks" / "loops" / ".apex-manifest.json"
        project_manifest.parent.mkdir(parents=True, exist_ok=True)
        payload = {"managed_by": DOCTOR_MODULE.HOOK_MANAGED_BY, "files": [{"kind": "runtime"}]}
        project_manifest.write_text(json.dumps(payload), encoding="utf-8")
        for home, config_name in ((codex_home, "config.toml"), (claude_home, "settings.json")):
            (home / "apex").mkdir(parents=True, exist_ok=True)
            (home / "apex" / "manifest.json").write_text(json.dumps(payload), encoding="utf-8")
            (home / "hooks").mkdir(parents=True, exist_ok=True)
            (home / "hooks" / "apex_loop.py").write_text("# Runtime copy marker: Generated by ApexPowers apex-init-project-hooks.\n", encoding="utf-8")
            (home / config_name).write_text("apex_loop.py\n", encoding="utf-8")

    def test_healthy_installation_has_no_failures(self) -> None:
        """A complete installation reports zero failures."""

        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw) / "project"
            root.mkdir()
            codex_home = Path(raw) / "codex-home"
            claude_home = Path(raw) / "claude-home"
            self.seed_core_skills(root)
            self.seed_agent_mirrors(root)
            self.seed_workflow(root)
            self.seed_hook_install(root, codex_home, claude_home)

            result = self.run_doctor(root, codex_home, claude_home)
            payload = json.loads(result.stdout)

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(payload["summary"]["fail"], 0)
        statuses = {item["name"]: item["status"] for item in payload["checks"]}
        self.assertEqual(statuses["core-skills"], "pass")
        self.assertEqual(statuses["hook-consistency"], "pass")

    def test_missing_core_skill_is_failure(self) -> None:
        """Core skill entrypoints are hard requirements."""

        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw) / "project"
            root.mkdir()
            codex_home = Path(raw) / "codex-home"
            claude_home = Path(raw) / "claude-home"
            self.seed_core_skills(root, missing={"apex-init-project-hooks"})
            self.seed_agent_mirrors(root)
            self.seed_workflow(root)

            result = self.run_doctor(root, codex_home, claude_home)
            payload = json.loads(result.stdout)

        self.assertEqual(result.returncode, 1)
        checks = {item["name"]: item for item in payload["checks"]}
        self.assertEqual(checks["core-skills"]["status"], "fail")
        self.assertIn("apex-init-project-hooks", checks["core-skills"]["message"])

    def test_manifest_without_host_runtime_is_failure(self) -> None:
        """Installed manifests must agree with host config and runtime files."""

        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw) / "project"
            root.mkdir()
            codex_home = Path(raw) / "codex-home"
            claude_home = Path(raw) / "claude-home"
            self.seed_core_skills(root)
            self.seed_agent_mirrors(root)
            self.seed_workflow(root)
            project_manifest = root / "tasks" / "loops" / ".apex-manifest.json"
            project_manifest.parent.mkdir(parents=True, exist_ok=True)
            project_manifest.write_text(json.dumps({"managed_by": DOCTOR_MODULE.HOOK_MANAGED_BY, "files": []}), encoding="utf-8")

            result = self.run_doctor(root, codex_home, claude_home)
            payload = json.loads(result.stdout)

        self.assertEqual(result.returncode, 1)
        checks = {item["name"]: item for item in payload["checks"]}
        self.assertEqual(checks["project-hook-manifest"]["status"], "pass")
        self.assertEqual(checks["hook-consistency"]["status"], "fail")
        self.assertIn("codex-hook-runtime", checks["hook-consistency"]["message"])

    def test_missing_agent_mirrors_are_warning_only(self) -> None:
        """Mirror drift is actionable but not a hard doctor failure."""

        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw) / "project"
            root.mkdir()
            codex_home = Path(raw) / "codex-home"
            claude_home = Path(raw) / "claude-home"
            self.seed_core_skills(root)
            source = root / ".agents" / "developer.md"
            source.parent.mkdir(parents=True)
            source.write_text("---\nname: developer\n---\nDeveloper agent.\n", encoding="utf-8")
            self.seed_workflow(root)

            result = self.run_doctor(root, codex_home, claude_home)
            payload = json.loads(result.stdout)

        self.assertEqual(result.returncode, 0, result.stderr)
        checks = {item["name"]: item for item in payload["checks"]}
        self.assertEqual(checks["agent-mirrors"]["status"], "warn")
        self.assertEqual(payload["summary"]["fail"], 0)


if __name__ == "__main__":
    unittest.main()
