#!/usr/bin/env python3
"""Read-only health checks for an ApexPowers installation."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


GENERATED_AGENT_MARKER = "Generated from ApexPowers .agents source template"
HOOK_MANAGED_BY = "Generated by ApexPowers apex-init-project-hooks"
PROJECT_MANIFEST = Path("tasks/loops/.apex-manifest.json")
HOST_MANIFEST = Path("apex/manifest.json")
WORKFLOW_STATES = (
    "no_task",
    "planning",
    "implementing",
    "review_required",
    "validation_required",
    "done",
)
CORE_SKILLS = (
    "apex-doctor",
    "apex-grill-with-docs",
    "apex-init-project-agent",
    "apex-init-project-code",
    "apex-init-project-file",
    "apex-init-project-hooks",
    "apex-lean-review",
    "apex-session-init-codex",
    "apex-sync-agent-mirrors",
    "apex-to-issues",
    "apex-to-prd",
)


@dataclass(frozen=True)
class CheckResult:
    """One doctor finding."""

    name: str
    status: str
    message: str
    fix: str = ""
    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """JSON-serializable check result."""

        payload: dict[str, Any] = {
            "name": self.name,
            "status": self.status,
            "message": self.message,
        }
        if self.fix:
            payload["fix"] = self.fix
        if self.details:
            payload["details"] = self.details
        return payload


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""

    parser = argparse.ArgumentParser(description="Check ApexPowers installation health without writing files.")
    parser.add_argument("root", nargs="?", default=".", help="Project root. Defaults to current directory.")
    parser.add_argument("--codex-home", help="Codex agent root. Defaults to CODEX_HOME or ~/.codex.")
    parser.add_argument("--claude-home", help="Claude Code agent root. Defaults to CLAUDE_HOME or ~/.claude.")
    parser.add_argument("--json", action="store_true", help="Output machine-readable JSON.")
    return parser.parse_args()


def default_agent_home(env_name: str, dirname: str) -> Path:
    """Resolve an agent home from an environment variable or user home."""

    if env_name in os.environ:
        return Path(os.environ[env_name]).expanduser().resolve()
    return (Path.home() / dirname).resolve()


def safe_read_text(path: Path, limit: int = 1_000_000) -> str | None:
    """Read a small text file, returning None when unavailable."""

    if not path.is_file():
        return None
    try:
        return path.read_text(encoding="utf-8", errors="ignore")[:limit]
    except OSError:
        return None


def load_json(path: Path) -> tuple[dict[str, Any] | None, str | None]:
    """Read a JSON object and return an error string on failure."""

    text = safe_read_text(path)
    if text is None:
        return None, "missing"
    try:
        payload = json.loads(text)
    except json.JSONDecodeError as exc:
        return None, f"invalid json: {exc}"
    if not isinstance(payload, dict):
        return None, "json root is not an object"
    return payload, None


def check_root(root: Path) -> CheckResult:
    """Check that the selected project root exists."""

    if not root.is_dir():
        return CheckResult("project-root", "fail", f"Project root does not exist: {root}", "Pass an existing project root.")
    return CheckResult("project-root", "pass", f"Project root found: {root}")


def check_python() -> CheckResult:
    """Report the Python runtime used by doctor."""

    version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    if sys.version_info < (3, 10):
        return CheckResult("python-runtime", "fail", f"Python {version} is too old.", "Use Python 3.10+ for ApexPowers scripts.")
    return CheckResult("python-runtime", "pass", f"Python {version} is available.", details={"executable": sys.executable})


def check_core_skills(root: Path) -> CheckResult:
    """Check required ApexPowers skills and SKILL.md entrypoints."""

    skills_dir = root / ".codex" / "skills"
    if not skills_dir.is_dir():
        return CheckResult("core-skills", "fail", ".codex/skills is missing.", "Copy ApexPowers .codex/skills into the project.")

    missing = [name for name in CORE_SKILLS if not (skills_dir / name / "SKILL.md").is_file()]
    if missing:
        return CheckResult(
            "core-skills",
            "fail",
            f"Missing core skill entrypoints: {', '.join(missing)}",
            "Reinstall or copy the missing ApexPowers skills.",
            {"missing": missing},
        )
    return CheckResult("core-skills", "pass", f"{len(CORE_SKILLS)} core ApexPowers skills are present.")


def source_agent_files(root: Path) -> list[Path]:
    """Return source .agents templates."""

    source_dir = root / ".agents"
    if not source_dir.is_dir():
        return []
    return sorted(path for path in source_dir.glob("*.md") if path.name.lower() != "agents.md")


def check_agent_mirrors(root: Path) -> CheckResult:
    """Check source agent templates and generated official mirrors."""

    sources = source_agent_files(root)
    if not sources:
        return CheckResult("agent-mirrors", "warn", "No .agents source templates found.", "Install .agents/*.md if this project should expose custom agents.")

    warnings: list[str] = []
    for source in sources:
        name = source.stem
        for mirror in (root / ".codex" / "agents" / f"{name}.toml", root / ".claude" / "agents" / f"{name}.md"):
            mirror_text = safe_read_text(mirror)
            if mirror_text is None:
                warnings.append(f"missing {mirror.relative_to(root).as_posix()}")
                continue
            if GENERATED_AGENT_MARKER not in mirror_text:
                warnings.append(f"missing generated marker in {mirror.relative_to(root).as_posix()}")
                continue
            try:
                if mirror.stat().st_mtime + 1 < source.stat().st_mtime:
                    warnings.append(f"older than source {mirror.relative_to(root).as_posix()}")
            except OSError:
                warnings.append(f"cannot stat {mirror.relative_to(root).as_posix()}")

    if warnings:
        return CheckResult(
            "agent-mirrors",
            "warn",
            f"Agent mirror issues found: {len(warnings)}",
            "Run apex-sync-agent-mirrors with --target all --write.",
            {"issues": warnings, "source_count": len(sources)},
        )
    return CheckResult("agent-mirrors", "pass", f"{len(sources)} source agent templates have generated Codex and Claude mirrors.")


def check_project_manifest(root: Path) -> CheckResult:
    """Check the project-level hook ownership manifest."""

    path = root / PROJECT_MANIFEST
    payload, error = load_json(path)
    if error == "missing":
        return CheckResult("project-hook-manifest", "warn", "Project hook manifest is not installed.", "Run apex-init-project-hooks --write if this project should use loop hooks.")
    if error:
        return CheckResult("project-hook-manifest", "fail", f"Project hook manifest is invalid: {error}", "Regenerate hooks with apex-init-project-hooks --update --write.")
    if payload.get("managed_by") != HOOK_MANAGED_BY:
        return CheckResult("project-hook-manifest", "fail", "Project hook manifest is not managed by ApexPowers.", "Inspect the manifest before reinstalling hooks.")
    files = payload.get("files", [])
    if not isinstance(files, list):
        return CheckResult("project-hook-manifest", "fail", "Project hook manifest has no valid files array.", "Regenerate hooks with apex-init-project-hooks --update --write.")
    return CheckResult("project-hook-manifest", "pass", f"Project hook manifest tracks {len(files)} files.")


def check_host_manifest(host: str, home: Path) -> CheckResult:
    """Check one host manifest file."""

    path = home / HOST_MANIFEST
    payload, error = load_json(path)
    if error == "missing":
        return CheckResult(f"{host}-host-manifest", "warn", f"{host} host manifest is not installed.", "Run apex-init-project-hooks --write with the expected agent home.")
    if error:
        return CheckResult(f"{host}-host-manifest", "fail", f"{host} host manifest is invalid: {error}", "Regenerate hooks with apex-init-project-hooks --update --write.")
    if payload.get("managed_by") != HOOK_MANAGED_BY:
        return CheckResult(f"{host}-host-manifest", "fail", f"{host} host manifest is not managed by ApexPowers.", "Inspect the manifest before reinstalling hooks.")
    return CheckResult(f"{host}-host-manifest", "pass", f"{host} host manifest is present.")


def check_host_runtime(host: str, home: Path) -> CheckResult:
    """Check one host runtime copy."""

    runtime = home / "hooks" / "apex_loop.py"
    text = safe_read_text(runtime)
    if text is None:
        return CheckResult(f"{host}-hook-runtime", "warn", f"{host} Apex hook runtime is not installed.", "Run apex-init-project-hooks --write with the expected agent home.")
    if HOOK_MANAGED_BY not in text and "ApexPowers apex-init-project-hooks" not in text:
        return CheckResult(f"{host}-hook-runtime", "fail", f"{host} hook runtime lacks the ApexPowers generated marker.", "Do not overwrite hand-written hooks; reinstall with --force only if intended.")
    return CheckResult(f"{host}-hook-runtime", "pass", f"{host} Apex hook runtime is present.")


def check_codex_config(codex_home: Path) -> CheckResult:
    """Check Codex hook config for Apex-managed entries."""

    toml_text = safe_read_text(codex_home / "config.toml")
    json_text = safe_read_text(codex_home / "hooks.json")
    if toml_text and "apex_loop.py" in toml_text:
        return CheckResult("codex-hook-config", "pass", "Codex config.toml contains Apex hook entries.")
    if json_text and "apex_loop.py" in json_text:
        return CheckResult("codex-hook-config", "pass", "Codex hooks.json contains Apex hook entries.")
    return CheckResult("codex-hook-config", "warn", "Codex hook config has no Apex hook entries.", "Run apex-init-project-hooks --write with the expected Codex home.")


def check_claude_config(claude_home: Path) -> CheckResult:
    """Check Claude Code settings for Apex-managed entries."""

    text = safe_read_text(claude_home / "settings.json")
    if text and "apex_loop.py" in text:
        return CheckResult("claude-hook-config", "pass", "Claude Code settings.json contains Apex hook entries.")
    return CheckResult("claude-hook-config", "warn", "Claude Code settings.json has no Apex hook entries.", "Run apex-init-project-hooks --write with the expected Claude home.")


def check_hook_consistency(results: list[CheckResult]) -> CheckResult:
    """Promote installed manifest/config mismatches to a hard failure."""

    by_name = {result.name: result for result in results}
    installed = any(by_name[name].status == "pass" for name in ("project-hook-manifest", "codex-host-manifest", "claude-host-manifest") if name in by_name)
    if not installed:
        return CheckResult("hook-consistency", "warn", "Loop hooks do not appear to be installed.", "Run apex-init-project-hooks --write when hooks are desired.")

    broken = [
        result.name
        for result in results
        if result.name
        in {
            "codex-host-manifest",
            "claude-host-manifest",
            "codex-hook-runtime",
            "claude-hook-runtime",
            "codex-hook-config",
            "claude-hook-config",
        }
        and result.status != "pass"
    ]
    if broken:
        return CheckResult(
            "hook-consistency",
            "fail",
            f"Hook manifest/config/runtime mismatch: {', '.join(broken)}",
            "Run apex-init-project-hooks --update --write with the same agent homes.",
            {"broken": broken},
        )
    return CheckResult("hook-consistency", "pass", "Loop hook manifest, config, and runtime agree.")


def check_workflow_state(root: Path) -> CheckResult:
    """Check the editable workflow-state file."""

    path = root / "tasks" / "loops" / "workflow.md"
    text = safe_read_text(path)
    if text is None:
        return CheckResult("workflow-state", "warn", "tasks/loops/workflow.md is missing.", "Run apex-init-project-hooks --write or restore the workflow state file.")
    missing = [state for state in WORKFLOW_STATES if f"[apex-state:{state}]" not in text or f"[/apex-state:{state}]" not in text]
    if missing:
        return CheckResult(
            "workflow-state",
            "fail",
            f"workflow.md is missing state blocks: {', '.join(missing)}",
            "Restore the missing [apex-state:*] blocks from apex-init-project-hooks.",
            {"missing": missing},
        )
    return CheckResult("workflow-state", "pass", f"workflow.md contains {len(WORKFLOW_STATES)} Apex workflow states.")


def check_git_status(root: Path) -> CheckResult:
    """Report whether the project has uncommitted changes."""

    if not (root / ".git").exists():
        return CheckResult("git-status", "warn", "Project is not a git repository.", "Run doctor from a git-backed project when possible.")
    result = subprocess.run(["git", "status", "--short"], cwd=root, text=True, encoding="utf-8", errors="replace", stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
    if result.returncode != 0:
        return CheckResult("git-status", "warn", f"git status failed: {result.stderr.strip()}", "Check git installation and repository state.")
    lines = [line for line in result.stdout.splitlines() if line.strip()]
    if lines:
        return CheckResult("git-status", "warn", f"Working tree has {len(lines)} uncommitted entries.", "Review changes before installing, updating, or committing ApexPowers files.", {"entries": lines[:20]})
    return CheckResult("git-status", "pass", "Working tree is clean.")


def run_checks(root: Path, codex_home: Path, claude_home: Path) -> list[CheckResult]:
    """Run all doctor checks."""

    results = [
        check_root(root),
        check_python(),
        check_core_skills(root),
        check_agent_mirrors(root),
        check_project_manifest(root),
        check_host_manifest("codex", codex_home),
        check_host_manifest("claude", claude_home),
        check_host_runtime("codex", codex_home),
        check_host_runtime("claude", claude_home),
        check_codex_config(codex_home),
        check_claude_config(claude_home),
        check_workflow_state(root),
        check_git_status(root),
    ]
    results.append(check_hook_consistency(results))
    return results


def summary(results: list[CheckResult]) -> dict[str, int]:
    """Count results by status."""

    return {status: sum(1 for result in results if result.status == status) for status in ("pass", "warn", "fail")}


def print_text(root: Path, codex_home: Path, claude_home: Path, results: list[CheckResult]) -> None:
    """Render human-readable output."""

    counts = summary(results)
    print(f"Apex Doctor: {root}")
    print(f"Codex home: {codex_home}")
    print(f"Claude home: {claude_home}")
    for result in results:
        print(f"[{result.status.upper()}] {result.name}: {result.message}")
        if result.fix:
            print(f"  fix: {result.fix}")
    print(f"Summary: {counts['pass']} pass, {counts['warn']} warn, {counts['fail']} fail.")


def print_json(root: Path, codex_home: Path, claude_home: Path, results: list[CheckResult]) -> None:
    """Render machine-readable output."""

    payload = {
        "root": str(root),
        "codex_home": str(codex_home),
        "claude_home": str(claude_home),
        "summary": summary(results),
        "checks": [result.to_dict() for result in results],
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))


def main() -> int:
    """CLI entrypoint."""

    args = parse_args()
    root = Path(args.root).expanduser().resolve()
    codex_home = (Path(args.codex_home).expanduser().resolve() if args.codex_home else default_agent_home("CODEX_HOME", ".codex"))
    claude_home = (Path(args.claude_home).expanduser().resolve() if args.claude_home else default_agent_home("CLAUDE_HOME", ".claude"))
    results = run_checks(root, codex_home, claude_home)
    if args.json:
        print_json(root, codex_home, claude_home, results)
    else:
        print_text(root, codex_home, claude_home, results)
    return 1 if any(result.status == "fail" for result in results) else 0


if __name__ == "__main__":
    raise SystemExit(main())
