"""Route registry and data models for Apex loop hooks."""

from __future__ import annotations

# Runtime copy marker: Generated by ApexPowers apex-init-project-hooks.

import json
from dataclasses import dataclass
from typing import Any


GENERATED_MARKER = "Generated by ApexPowers apex-init-project-hooks"
SOURCE_EXTENSIONS = {".py", ".ts", ".tsx", ".js", ".jsx", ".go", ".rs", ".java", ".cs", ".vue", ".svelte"}
FRONTEND_EXTENSIONS = {".tsx", ".jsx", ".vue", ".svelte"}
BACKEND_EXTENSIONS = {".py", ".go", ".rs", ".java", ".cs"}
SECRET_NAME_PATTERNS = (
    ".env",
    ".npmrc",
    ".pypirc",
    "id_rsa",
    "id_dsa",
    "id_ed25519",
    "credentials",
    "credential",
    "token",
    "secret",
    "private-key",
)
SECRET_ALLOWLIST_SUFFIXES = (".example", ".sample", ".template", ".md")
GENERATED_PATH_PARTS = {
    "node_modules",
    "vendor",
    "dist",
    "build",
    "coverage",
    "__snapshots__",
    "fixtures",
    "fixture",
    "migrations",
    "generated",
}


@dataclass(frozen=True)
class Route:
    """Stable hook route exposed to host adapter configuration."""

    event: str
    route_id: str
    command: str
    handler: str
    codex_matcher: str | None = None
    claude_matcher: str | None = None

    def matcher_for(self, host: str) -> str | None:
        """Matcher value for a host adapter."""

        if host == "codex":
            return self.codex_matcher
        return self.claude_matcher


class RouteRegistry:
    """Single source of truth for hook event routing."""

    def __init__(self) -> None:
        """Route list arranged in stable host adapter order."""

        self._routes = [
            Route("SessionStart", "default", "session-start", "session_start"),
            Route("UserPromptSubmit", "default", "user-prompt-submit", "user_prompt_submit"),
            Route(
                "PreToolUse",
                "safety",
                "pre-tool-use",
                "pre_tool_use",
                "Bash|Shell|PowerShell|Edit|Write|MultiEdit|apply_patch",
                "Bash|Shell|PowerShell|Edit|Write|MultiEdit",
            ),
            Route("PostToolUse", "edit", "post-tool-use", "post_tool_use", "Edit|Write|MultiEdit|apply_patch", "Edit|Write|MultiEdit"),
            Route("PostToolUse", "bash", "post-tool-use", "post_tool_use", "Bash|Shell|PowerShell", "Bash|Shell|PowerShell"),
            Route("PostToolUse", "always", "post-tool-use", "post_tool_use"),
            Route("Stop", "default", "stop", "stop"),
        ]

    def routes(self) -> list[Route]:
        """Routes in stable adapter order."""

        return list(self._routes)

    def event_names(self) -> list[str]:
        """Unique event names in adapter order."""

        names: list[str] = []
        for route in self._routes:
            if route.event not in names:
                names.append(route.event)
        return names


class HostConfigRenderer:
    """Renderer for Claude Code and Codex hook JSON."""

    def __init__(self, registry: RouteRegistry) -> None:
        """Registry-backed renderer."""

        self._registry = registry

    def render(self, host: str, script_path: str) -> str:
        """Render a host hook configuration document."""

        hooks: dict[str, list[dict[str, Any]]] = {event: [] for event in self._registry.event_names()}
        for route in self._registry.routes():
            entry: dict[str, Any] = {
                "hooks": [
                    {
                        "type": "command",
                        "command": self._command(script_path, route.command, host, route.route_id),
                        "timeout": 30,
                    }
                ]
            }
            matcher = route.matcher_for(host)
            if matcher:
                entry["matcher"] = matcher
            hooks[route.event].append(entry)

        payload = {"hooks": hooks}
        return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"

    def _command(self, script_path: str, command: str, host: str, route_id: str) -> str:
        """Shell command used by host adapters."""

        normalized = script_path.replace("\\", "/")
        return f'python "{normalized}" {command} --host {host} --route {route_id}'


@dataclass
class StructuredFailure:
    """Machine-readable guard finding."""

    guard: str
    reason: str
    fix: str
    failure_class: str
    run_id: str
    action: str = "block"

    def to_dict(self) -> dict[str, str]:
        """JSON-serializable representation."""

        return {
            "guard": self.guard,
            "action": self.action,
            "reason": self.reason,
            "fix": self.fix,
            "failure_class": self.failure_class,
            "run_id": self.run_id,
        }

    def message(self) -> str:
        """Human-readable one-line summary."""

        return f"[{self.guard}] {self.reason} Fix: {self.fix}"
