"""Utilities and repo state helpers for Apex loop hooks."""

from __future__ import annotations

# Runtime copy marker: Generated by ApexPowers apex-init-project-hooks.

import json
import hashlib
import os
import re
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

from apex_loop_routes import (
    BACKEND_EXTENSIONS,
    FRONTEND_EXTENSIONS,
    GENERATED_MARKER,
    GENERATED_PATH_PARTS,
    SECRET_ALLOWLIST_SUFFIXES,
    SECRET_NAME_PATTERNS,
    SOURCE_EXTENSIONS,
    StructuredFailure,
)


WORKFLOW_PATH = Path("tasks") / "loops" / "workflow.md"
WORKFLOW_BLOCK_PATTERN = re.compile(r"\[apex-state:([A-Za-z0-9_-]+)\](.*?)\[/apex-state:\1\]", re.S)


@dataclass(frozen=True)
class WorkflowState:
    """Resolved workflow state block for hook context injection."""

    status: str
    body: str
    source: str


class HookInput:
    """Parsed hook input with tolerant host-field extraction."""

    def __init__(self, payload: dict[str, Any], raw: str) -> None:
        """Hook payload and raw stdin."""

        self.payload = payload
        self.raw = raw

    @classmethod
    def from_stdin(cls) -> "HookInput":
        """Read JSON hook input from stdin."""

        raw = sys.stdin.read()
        if not raw.strip():
            return cls({}, raw)
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError:
            return cls({"raw_input": raw}, raw)
        if isinstance(parsed, dict):
            return cls(parsed, raw)
        return cls({"value": parsed}, raw)

    def command_text(self) -> str:
        """Best-effort shell command text from host payload."""

        return first_string(self.payload, {"command", "cmd", "script", "shell_command"})

    def prompt_text(self) -> str:
        """Best-effort user prompt text from host payload."""

        return first_string(self.payload, {"prompt", "user_prompt", "message"})

    def run_id(self) -> str:
        """Stable run id from host fields or generated fallback."""

        value = first_string(self.payload, {"run_id", "session_id", "conversation_id"})
        if value:
            return safe_slug(value, "run")
        for key in ("HOOK_RUN_ID", "CLAUDE_RUN_ID", "CODEX_RUN_ID"):
            if os.environ.get(key):
                return safe_slug(str(os.environ[key]), "run")
        return f"run-{time.strftime('%Y%m%dT%H%M%S')}-{os.getpid()}"

    def file_paths(self) -> list[str]:
        """Best-effort changed file paths from host payload."""

        paths: list[str] = []
        collect_values(self.payload, {"file_path", "path", "target_file", "relative_path", "file"}, paths)
        return unique_strings(paths)


class HookContext:
    """Runtime context shared by guards."""

    def __init__(self, repo_root: Path, hook_input: HookInput, host: str, route: str) -> None:
        """Project root, hook input, and host metadata."""

        self.repo_root = repo_root
        self.hook_input = hook_input
        self.host = host
        self.route = route
        self.run_id = hook_input.run_id()

    @classmethod
    def create(cls, args: Any) -> "HookContext":
        """Create context from CLI args and stdin."""

        hook_input = HookInput.from_stdin()
        repo_root = resolve_repo_root(Path(args.repo_root).resolve() if args.repo_root else Path.cwd())
        return cls(repo_root, hook_input, args.host, args.route)

    def rel_path(self, path_value: str) -> Path | None:
        """Resolve a host path safely inside the repo."""

        cleaned = path_value.strip().strip('"').strip("'").replace("\\", "/")
        if not cleaned:
            return None
        candidate = Path(cleaned)
        if not candidate.is_absolute():
            candidate = self.repo_root / candidate
        try:
            resolved = candidate.resolve()
            resolved.relative_to(self.repo_root)
        except (OSError, ValueError):
            return None
        return resolved.relative_to(self.repo_root)

    def absolute(self, rel_path: Path) -> Path:
        """Absolute path for a repo-relative path."""

        return self.repo_root / rel_path

    def git(self, args: list[str]) -> subprocess.CompletedProcess[str]:
        """Run a git command inside the repo."""

        return subprocess.run(
            ["git", *args],
            cwd=self.repo_root,
            text=True,
            encoding="utf-8",
            errors="replace",
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )

    def changed_files(self) -> list[str]:
        """Changed and untracked files relative to HEAD."""

        names: set[str] = set()
        for args in (["diff", "--name-only", "HEAD"], ["ls-files", "--others", "--exclude-standard"]):
            result = self.git(args)
            if result.returncode == 0:
                names.update(line.strip().replace("\\", "/") for line in result.stdout.splitlines() if line.strip())
        return sorted(names)

    def write_failure(self, failure: StructuredFailure, slug: str | None = None) -> None:
        """Append a structured failure record to tasks/loops."""

        loops_dir = self.repo_root / "tasks" / "loops"
        if slug:
            loops_dir = loops_dir / safe_slug(slug, "task")
        loops_dir.mkdir(parents=True, exist_ok=True)
        record = {"ts": time.strftime("%Y-%m-%dT%H:%M:%S%z"), **failure.to_dict()}
        with (loops_dir / "failures.jsonl").open("a", encoding="utf-8", newline="\n") as handle:
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")


def first_string(value: Any, keys: set[str]) -> str:
    """First string value found for a set of key names."""

    if isinstance(value, dict):
        for key, item in value.items():
            if key in keys and isinstance(item, str):
                return item.strip()
            nested = first_string(item, keys)
            if nested:
                return nested
    elif isinstance(value, list):
        for item in value:
            nested = first_string(item, keys)
            if nested:
                return nested
    return ""


def collect_values(value: Any, keys: set[str], output: list[str]) -> None:
    """Collect string values for known keys."""

    if isinstance(value, dict):
        for key, item in value.items():
            if key in keys and isinstance(item, str):
                output.append(item)
            else:
                collect_values(item, keys, output)
    elif isinstance(value, list):
        for item in value:
            collect_values(item, keys, output)


def unique_strings(values: Iterable[str]) -> list[str]:
    """Unique non-empty strings preserving order."""

    seen: set[str] = set()
    output: list[str] = []
    for value in values:
        normalized = value.strip()
        if normalized and normalized not in seen:
            seen.add(normalized)
            output.append(normalized)
    return output


def resolve_repo_root(start: Path) -> Path:
    """Resolve git root, falling back to the current directory."""

    result = subprocess.run(
        ["git", "-C", str(start), "rev-parse", "--show-toplevel"],
        text=True,
        encoding="utf-8",
        errors="replace",
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode == 0 and result.stdout.strip():
        return Path(result.stdout.strip()).resolve()
    return start.resolve()


def safe_slug(value: str, fallback: str) -> str:
    """Filesystem-safe slug."""

    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip()).strip("-._")
    return slug or fallback


def is_secret_path(path: Path) -> bool:
    """Whether a repo path is a protected secret-like path."""

    names = [part.lower() for part in path.parts]
    name = names[-1] if names else ""
    if any(name.endswith(suffix) for suffix in SECRET_ALLOWLIST_SUFFIXES):
        return False
    return any(is_secret_name(part) for part in names)


def is_secret_name(name: str) -> bool:
    """Whether one path segment is an explicit secret-like name."""

    exact_names = {".npmrc", ".pypirc", "id_rsa", "id_dsa", "id_ed25519"}
    if name in exact_names or name == ".env" or name.startswith(".env."):
        return True

    canonical = name.replace("_", "-")
    if re.search(r"(^|[.-])private-key($|[.-])", canonical):
        return True

    tokens = set(re.split(r"[._\-\s]+", name))
    sensitive_tokens = set(SECRET_NAME_PATTERNS) - exact_names - {".env", ".npmrc", ".pypirc", "id_rsa", "id_dsa", "id_ed25519", "private-key"}
    return bool(tokens & sensitive_tokens)


def is_source_file(path: Path) -> bool:
    """Whether a path is a source file checked by line-length guard."""

    return path.suffix.lower() in SOURCE_EXTENSIONS


def is_generated_exception(path: Path) -> bool:
    """Whether a path is exempt from file-size checks."""

    text = path.as_posix().lower()
    parts = set(path.parts)
    if parts & GENERATED_PATH_PARTS:
        return True
    return any(token in text for token in (".lock", ".min.", "generated", "snapshot"))


def thresholds_for(path: Path) -> tuple[int, int, str]:
    """Warning, hard limit, and target range for a file."""

    suffix = path.suffix.lower()
    if suffix in FRONTEND_EXTENSIONS:
        return 400, 500, "200-250 effective lines"
    if suffix in BACKEND_EXTENSIONS:
        return 400, 500, "up to 300 effective lines"
    return 400, 500, "150-300 effective lines"


def count_effective_lines(path: Path) -> int:
    """Count non-empty, non-comment source lines."""

    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return 0
    in_block = False
    count = 0
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if in_block:
            if "*/" in line or "-->" in line:
                in_block = False
            continue
        if line.startswith(("/*", "<!--")):
            if "*/" not in line and "-->" not in line:
                in_block = True
            continue
        if line.startswith(("//", "#", "*", "<!--")):
            continue
        count += 1
    return count


def context_paths_or_changed(context: HookContext) -> list[Path]:
    """Paths from hook input, falling back to git changes."""

    output: list[Path] = []
    for raw_path in context.hook_input.file_paths():
        rel_path = context.rel_path(raw_path)
        if rel_path:
            output.append(rel_path)
    if not output:
        output.extend(Path(path) for path in context.changed_files())
    return output


def is_reviewable_code_path(path: Path) -> bool:
    """Whether a changed file should trigger review."""

    if not is_source_file(path):
        return False
    text = path.as_posix()
    return not text.startswith(("tasks/", "plans/", "docs/", ".codex/agents/", ".claude/agents/"))


def newest_todo(repo_root: Path) -> Path | None:
    """Newest tasks/todo+*.md file."""

    tasks_dir = repo_root / "tasks"
    if not tasks_dir.is_dir():
        return None
    todos = list(tasks_dir.glob("todo+*.md"))
    return max(todos, key=lambda path: path.stat().st_mtime) if todos else None


def review_status(path: Path) -> str:
    """Review file status: missing, ready, issues, or pending."""

    if not path.exists():
        return "missing"
    text = path.read_text(encoding="utf-8", errors="ignore").lower()
    if "status**: ready" in text or "status: ready" in text or "external acceptance**: pass" in text:
        return "ready"
    if any(token in text for token in ("critical", "warning", "blocker", "must fix", "p0", "p1")):
        return "issues"
    return "pending"


def validation_status(path: Path) -> str:
    """Validation status declared in a review file."""

    if not path.exists():
        return "missing"

    text = path.read_text(encoding="utf-8", errors="ignore").lower()
    labels = ("validation", "verification", "tests", "test", "quality gate", "external acceptance")
    if has_labeled_status(text, labels, ("fail", "failed", "failing", "red")):
        return "failed"
    if has_labeled_status(text, labels, ("pass", "passed", "ok", "green", "success", "succeeded")):
        return "pass"
    return "missing"


def has_labeled_status(text: str, labels: Iterable[str], values: Iterable[str]) -> bool:
    """Whether text contains a labeled markdown status."""

    value_pattern = "|".join(re.escape(value) for value in values)
    for label in labels:
        label_pattern = re.escape(label)
        if re.search(rf"\*{{0,2}}{label_pattern}\*{{0,2}}\s*:\s*({value_pattern})\b", text):
            return True
    return False


def loop_state_path(repo_root: Path, slug: str) -> Path:
    """Path to machine-readable loop state for a task slug."""

    return repo_root / "tasks" / "loops" / slug / "state.json"


def read_loop_state(repo_root: Path, slug: str) -> dict[str, Any]:
    """Current loop state, or an empty mapping when absent or invalid."""

    state_path = loop_state_path(repo_root, slug)
    if not state_path.is_file():
        return {}
    try:
        state = json.loads(state_path.read_text(encoding="utf-8", errors="ignore"))
    except json.JSONDecodeError:
        return {}
    return state if isinstance(state, dict) else {}


def code_file_fingerprints(repo_root: Path, code_files: Iterable[str]) -> dict[str, str]:
    """Stable content fingerprints for review coverage checks."""

    output: dict[str, str] = {}
    for raw_path in sorted(set(code_files)):
        rel_path = Path(raw_path)
        absolute = repo_root / rel_path
        if not absolute.is_file():
            output[rel_path.as_posix()] = "missing"
            continue
        try:
            digest = hashlib.sha256(absolute.read_bytes()).hexdigest()
        except OSError:
            digest = "unreadable"
        output[rel_path.as_posix()] = f"sha256:{digest}"
    return output


def review_scope_files(review_path: Path) -> set[str]:
    """File paths listed in a generated review request scope."""

    if not review_path.is_file():
        return set()
    text = review_path.read_text(encoding="utf-8", errors="ignore")
    return {match.group(1).replace("\\", "/") for match in re.finditer(r"^- `([^`]+)`\s*$", text, re.M)}


def review_covers_current_code(repo_root: Path, slug: str, review_path: Path, code_files: list[str]) -> bool:
    """Whether current code changes are still covered by passed review evidence."""

    current_files = {Path(path).as_posix() for path in code_files}
    if not current_files:
        return True

    state = read_loop_state(repo_root, slug)
    stored_hashes = state.get("changed_file_hashes")
    if isinstance(stored_hashes, dict) and stored_hashes:
        current_hashes = code_file_fingerprints(repo_root, current_files)
        return current_files.issubset(set(stored_hashes)) and all(current_hashes[path] == stored_hashes.get(path) for path in current_files)

    scoped_files = review_scope_files(review_path)
    if not current_files.issubset(scoped_files):
        return False
    if not review_path.is_file():
        return False

    review_mtime = review_path.stat().st_mtime
    for raw_path in current_files:
        absolute = repo_root / raw_path
        if absolute.exists() and absolute.stat().st_mtime > review_mtime:
            return False
    return True


def workflow_blocks(repo_root: Path) -> dict[str, str]:
    """Workflow-state blocks defined by the editable workflow document."""

    path = repo_root / WORKFLOW_PATH
    if not path.is_file():
        return {}
    text = path.read_text(encoding="utf-8", errors="ignore")
    blocks: dict[str, str] = {}
    for match in WORKFLOW_BLOCK_PATTERN.finditer(text):
        blocks[match.group(1).strip().lower()] = match.group(2).strip()
    return blocks


def workflow_status(repo_root: Path, changed: list[str] | None = None) -> str:
    """Current workflow status inferred from loop artifacts."""

    todo_path = newest_todo(repo_root)
    if not todo_path:
        return "no_task"

    changed_files = changed if changed is not None else git_changed_files(repo_root)
    slug = safe_slug(todo_path.stem.removeprefix("todo+"), "task")
    review_path = repo_root / "tasks" / "reviews" / f"{slug}.md"
    status = review_status(review_path)
    validation = validation_status(review_path)
    code_changed = any(is_reviewable_code_path(Path(path)) for path in changed_files)

    if status == "ready":
        if validation != "pass":
            return "validation_required"
        return "done" if review_covers_current_code(repo_root, slug, review_path, [path for path in changed_files if is_reviewable_code_path(Path(path))]) else "review_required"
    if status in {"pending", "issues"} or code_changed:
        return "review_required"

    state_phase = loop_state_phase(repo_root, slug)
    if state_phase:
        return state_phase
    return "planning"


def git_changed_files(repo_root: Path) -> list[str]:
    """Changed and untracked files without needing a HookContext instance."""

    names: set[str] = set()
    for args in (["diff", "--name-only", "HEAD"], ["ls-files", "--others", "--exclude-standard"]):
        result = subprocess.run(
            ["git", *args],
            cwd=repo_root,
            text=True,
            encoding="utf-8",
            errors="replace",
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if result.returncode == 0:
            names.update(line.strip().replace("\\", "/") for line in result.stdout.splitlines() if line.strip())
    return sorted(names)


def loop_state_phase(repo_root: Path, slug: str) -> str:
    """Stored loop phase when it matches a known workflow state."""

    state = read_loop_state(repo_root, slug)
    phase = state.get("phase")
    if isinstance(phase, str) and phase in {"planning", "implementing", "review_required", "validation_required", "done"}:
        return phase
    return ""


def resolve_workflow_state(repo_root: Path, changed: list[str] | None = None) -> WorkflowState:
    """Workflow-state block selected for the current repo state."""

    status = workflow_status(repo_root, changed)
    blocks = workflow_blocks(repo_root)
    body = blocks.get(status) or fallback_workflow_body(status)
    source = WORKFLOW_PATH.as_posix() if status in blocks else "fallback"
    return WorkflowState(status=status, body=body, source=source)


def fallback_workflow_body(status: str) -> str:
    """Fallback state guidance used when workflow.md is missing or incomplete."""

    bodies = {
        "no_task": "No active todo was found. Answer direct questions normally or create a todo before implementation.",
        "planning": "An active todo exists. Clarify scope and validation before changing code.",
        "implementing": "Implementation is in progress. Keep changes scoped and preserve user edits.",
        "review_required": "Code changes require review before completion.",
        "validation_required": "Review is ready, but validation evidence is missing or failing.",
        "done": "Review and validation are complete.",
    }
    return bodies.get(status, "Continue with the current Apex loop state.")


def workflow_state_context(repo_root: Path, changed: list[str] | None = None) -> str:
    """XML-like workflow-state block suitable for hook stdout or context."""

    state = resolve_workflow_state(repo_root, changed)
    return f'<apex-workflow-state status="{state.status}" source="{state.source}">\n{state.body}\n</apex-workflow-state>'


def update_loop_state(repo_root: Path, slug: str, todo_path: Path, review_path: Path, code_files: list[str], run_id: str, phase: str = "review_required") -> int:
    """Update loop state and return review attempts."""

    state_dir = repo_root / "tasks" / "loops" / slug
    state_dir.mkdir(parents=True, exist_ok=True)
    state_path = loop_state_path(repo_root, slug)
    state = read_loop_state(repo_root, slug)
    review = state.setdefault("review", {})
    attempts = int(review.get("attempts", 0)) + 1
    state.update(
        {
            "version": 1,
            "slug": slug,
            "phase": phase,
            "todo_path": todo_path.relative_to(repo_root).as_posix(),
            "changed_files": code_files,
            "changed_file_hashes": code_file_fingerprints(repo_root, code_files),
            "updated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        }
    )
    review.update({"required": True, "status": "pending", "attempts": attempts, "review_path": review_path.relative_to(repo_root).as_posix(), "run_id": run_id})
    state_path.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    return attempts


def write_review_request(repo_root: Path, slug: str, todo_path: Path, review_path: Path, code_files: list[str], run_id: str) -> None:
    """Create a review request file."""

    review_path.parent.mkdir(parents=True, exist_ok=True)
    files = "\n".join(f"- `{path}`" for path in code_files)
    content = f"""# Review Request: {slug}

> **Generated By**: {GENERATED_MARKER}
> **Status**: Pending
> **Run ID**: {run_id}
> **Todo**: {todo_path.relative_to(repo_root).as_posix()}

## Scope

{files}

## Required Reviewer

调用 `code-reviewer` 审查本轮 diff。高风险任务可拆成 security、test-quality、maintainability、perf 维度。

## Completion Contract

review 通过后，把本文件状态改为：

`> **Status**: Ready`

验证通过后，在本文件记录：

`> **Validation**: Pass`

并在下方列出实际运行过的命令和结果摘要。

若列出 Critical / Warning / blocker / P0 / P1 问题，修复后再次 review。
"""
    review_path.write_text(content, encoding="utf-8", newline="\n")


def unresolved_reviews(repo_root: Path) -> list[str]:
    """Review files that still need attention."""

    review_dir = repo_root / "tasks" / "reviews"
    if not review_dir.is_dir():
        return []
    output: list[str] = []
    for path in sorted(review_dir.glob("*.md"), key=lambda item: item.stat().st_mtime, reverse=True):
        status = review_status(path)
        if status != "ready":
            output.append(f"{path.relative_to(repo_root).as_posix()} ({status})")
        elif validation_status(path) != "pass":
            output.append(f"{path.relative_to(repo_root).as_posix()} (validation-missing)")
    return output


def recent_lessons(repo_root: Path) -> list[str]:
    """Recent lessons from tasks/lessons.md."""

    path = repo_root / "tasks" / "lessons.md"
    if not path.is_file():
        return []
    lines = [line.strip(" -") for line in path.read_text(encoding="utf-8", errors="ignore").splitlines() if line.strip()]
    return lines[-3:]


def emit_warning_or_log(context: HookContext, failure: StructuredFailure) -> None:
    """Emit warning and persist structured record."""

    context.write_failure(failure)
    print(json.dumps(failure.to_dict(), ensure_ascii=False), file=sys.stderr)


def emit_failure(context: HookContext, failure: StructuredFailure, stop_decision: bool = False) -> int:
    """Emit a blocking failure."""

    context.write_failure(failure)
    if stop_decision:
        print(json.dumps({"decision": "block", "reason": failure.message()}, ensure_ascii=False))
    else:
        print(json.dumps(failure.to_dict(), ensure_ascii=False), file=sys.stderr)
    return 2
