"""Guard implementations and CLI dispatcher for Apex loop hooks."""

from __future__ import annotations

# Runtime copy marker: Generated by ApexPowers apex-init-project-hooks.

import argparse
import json
import re
from pathlib import Path

from apex_loop_routes import HostConfigRenderer, RouteRegistry, StructuredFailure
from apex_loop_utils import (
    HookContext,
    active_task,
    active_stop_blocker_message,
    cached_guard_result,
    context_paths_diff_aware,
    count_effective_lines,
    count_effective_lines_at_head,
    emit_failure,
    emit_warning_or_log,
    extract_pending_write_text,
    file_sha256,
    is_generated_exception,
    is_reviewable_code_path,
    is_secret_path,
    is_source_file,
    mark_security_required,
    mark_review_request_created,
    mentions_secret_path,
    migrate_reviews,
    parse_review_file,
    recent_lessons,
    record_active_stop_continuation,
    record_stop_blocker,
    review_covers_current_code,
    security_required_failure,
    reset_stop_blocker,
    resolve_workflow_state,
    review_status,
    should_skip_generated_or_large,
    thresholds_for,
    unresolved_reviews,
    update_guard_cache,
    update_loop_state,
    validation_status,
    workflow_state_context,
    write_review_request,
)


class SecurityGuard:
    """PreToolUse safety checks for commands and secret paths."""

    _dangerous_patterns = [
        (re.compile(r"\brm\s+-rf\s+(/|~|\$HOME|%USERPROFILE%|[A-Za-z]:\\?)", re.I), "危险递归删除"),
        (re.compile(r"\bgit\s+reset\s+--hard\b", re.I), "破坏性 git reset"),
        (re.compile(r"\bgit\s+checkout\s+--\b", re.I), "破坏性 git checkout"),
        (re.compile(r"\bgit\s+push\b.*\s--force", re.I), "force push"),
        (re.compile(r"(curl|wget|Invoke-WebRequest|iwr)\b.*(\||;).*(bash|sh|iex|Invoke-Expression)", re.I), "远程脚本管道执行"),
        (re.compile(r"\b(eval|Invoke-Expression|iex)\b", re.I), "动态执行字符串"),
    ]

    def run(self, context: HookContext) -> StructuredFailure | None:
        """Return the first blocking security failure."""

        command = context.hook_input.command_text()
        for pattern, label in self._dangerous_patterns:
            if command and pattern.search(command):
                return StructuredFailure(
                    "SecurityGuard",
                    f"{label}: {command[:180]}",
                    "让用户明确授权并说明风险，或改用更小范围、可逆的命令。",
                    "security_risk",
                    context.run_id,
                )

        for path_text in context.hook_input.file_paths():
            normalized = context.normalize_path(path_text)
            if not normalized.inside_repo:
                return StructuredFailure(
                    "PathGuard",
                    f"路径不在当前仓库内或包含不可安全解析的 traversal: {path_text}",
                    "只读取或写入仓库内路径；如确需访问外部路径，让用户手动确认后改用显式流程。",
                    "security_risk",
                    context.run_id,
                    event="PreToolUse",
                    subject=path_text,
                )
            if normalized.relative and is_secret_path(normalized.relative):
                return StructuredFailure(
                    "SecretPathGuard",
                    f"疑似 secrets 路径被访问: {normalized.relative.as_posix()}",
                    "不要读取或写入 secrets；改用 .env.example、占位变量或让用户手动处理。",
                    "security_risk",
                    context.run_id,
                    event="PreToolUse",
                    subject=normalized.relative.as_posix(),
                )
            if mentions_secret_path(path_text):
                return StructuredFailure(
                    "SecretPathGuard",
                    f"路径模式疑似覆盖 secrets: {path_text}",
                    "不要用 Read/Grep/Glob/MCP 工具访问 secrets；改用 .env.example 或让用户手动处理。",
                    "security_risk",
                    context.run_id,
                    event="PreToolUse",
                    subject=path_text,
                )

        for pending in extract_pending_write_text(context.hook_input.payload, context.host):
            if SecretContentGuard.contains_secret(pending.text):
                return StructuredFailure(
                    "SecretContentGuard",
                    f"{pending.source} 疑似包含 token、API key 或 private key，已在工具执行前阻断。",
                    "不要把真实密钥写入仓库；改用占位符、环境变量名、密钥管理器或 .env.example。",
                    "security_risk",
                    context.run_id,
                    action="deny",
                    event="PreToolUse",
                    effect="tool_prevented",
                    subject=pending.source,
                )
        return None


class LineLengthGuard:
    """PostToolUse file size checks using effective code lines."""

    def check(self, context: HookContext, paths: list[Path], block_hard_limit: bool) -> list[StructuredFailure]:
        """Check changed source files and return warnings or blocks."""

        findings: list[StructuredFailure] = []
        for rel_path in paths:
            if not is_source_file(rel_path) or is_generated_exception(rel_path):
                continue
            absolute = context.absolute(rel_path)
            if not absolute.is_file():
                continue
            lines = count_effective_lines(absolute)
            threshold = thresholds_for(rel_path)
            if lines > threshold.hard:
                previous_lines = count_effective_lines_at_head(context.repo_root, rel_path) if block_hard_limit else None
                should_block = block_hard_limit and (previous_lines is None or previous_lines <= threshold.hard)
                fix = f"{threshold.split_hint} 目标区间 {threshold.target}。"
                if not block_hard_limit:
                    fix += " 当前为 PostToolUse 提醒；Stop gate 会阻塞该问题。"
                elif previous_lines is not None and previous_lines > threshold.hard:
                    fix += f" 该文件在 HEAD 已有 {previous_lines} 有效行；本次作为 warning 记录，但 review 仍需关注。"
                findings.append(
                    StructuredFailure(
                        "LineLengthGuard",
                        f"{rel_path.as_posix()} ({threshold.category}) 有效代码行 {lines}，超过硬上限 {threshold.hard}。",
                        fix,
                        "quality_gate",
                        context.run_id,
                        action="block" if should_block else "warn",
                    )
                )
            elif lines > threshold.warning:
                findings.append(
                    StructuredFailure(
                        "LineLengthGuard",
                        f"{rel_path.as_posix()} ({threshold.category}) 有效代码行 {lines}，超过强提醒线 {threshold.warning}。",
                        f"评估分拆；{threshold.split_hint} 目标区间 {threshold.target}，超过 {threshold.hard} 会在 Stop gate 阻塞。",
                        "quality_gate",
                        context.run_id,
                        action="warn",
                    )
                )
        return findings


class SecretContentGuard:
    """PostToolUse scan for accidentally written credentials."""

    _secret_patterns = [
        re.compile(r"-----BEGIN (OPENSSH|RSA|DSA|EC) PRIVATE KEY-----"),
        re.compile(r"\bsk-[A-Za-z0-9_-]{20,}\b"),
        re.compile(r"\bghp_[A-Za-z0-9_]{20,}\b"),
        re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
        re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{20,}\b"),
    ]

    @classmethod
    def contains_secret(cls, text: str) -> bool:
        """Whether text contains secret-like content."""

        return any(pattern.search(text) for pattern in cls._secret_patterns)

    def check(self, context: HookContext, paths: list[Path]) -> StructuredFailure | None:
        """Return a follow-up finding when changed content looks secret-like."""

        for rel_path in paths:
            absolute = context.absolute(rel_path)
            if not absolute.is_file() or is_secret_path(rel_path):
                continue
            if should_skip_generated_or_large(rel_path, absolute):
                continue
            digest = file_sha256(absolute)
            cached = cached_guard_result(context.repo_root, "SecretContentGuard", rel_path, digest)
            if cached == "clean":
                continue
            try:
                text = absolute.read_text(encoding="utf-8", errors="ignore")[:200_000]
            except OSError:
                continue
            if self.contains_secret(text):
                update_guard_cache(context.repo_root, "SecretContentGuard", rel_path, digest, "secret", absolute)
                return StructuredFailure(
                    "SecretContentGuard",
                    f"{rel_path.as_posix()} 疑似包含 token、API key 或 private key。",
                    "PostToolUse 无法撤销已发生写入；请立即移除真实密钥，改用占位符、环境变量名或 .env.example，然后重新验证。",
                    "security_risk",
                    context.run_id,
                    action="feedback_block",
                    event="PostToolUse",
                    effect="tool_already_ran_followup_required",
                    subject=rel_path.as_posix(),
                )
            update_guard_cache(context.repo_root, "SecretContentGuard", rel_path, digest, "clean", absolute)
        return None


class MirrorDriftGuard:
    """Detect source agent changes without generated mirror changes."""

    def check(self, context: HookContext, block: bool) -> list[StructuredFailure]:
        """Return mirror drift findings."""

        changed = set(context.changed_files())
        findings: list[StructuredFailure] = []
        for source in sorted(path for path in changed if path.startswith(".agents/") and path.endswith(".md")):
            name = Path(source).stem
            if name.lower() == "agents":
                continue
            expected = {f".codex/agents/{name}.toml", f".claude/agents/{name}.md"}
            missing = sorted(expected - changed)
            if missing:
                findings.append(
                    StructuredFailure(
                        "MirrorDriftGuard",
                        f"{source} 已变化，但镜像未同步: {', '.join(missing)}",
                        "运行 python .codex\\skills\\apex-sync-agent-mirrors\\scripts\\sync_agent_mirrors.py . --target all --write",
                        "missing_artifact",
                        context.run_id,
                        action="block" if block else "warn",
                    )
                )
        return findings


class ContractGate:
    """Stop gate that blocks completion when the active todo still has open work."""

    _OPEN_CHECKBOX_PATTERN = re.compile(r"^\s*[-*]\s+\[\s\]\s+(.+?)\s*$")

    def run(self, context: HookContext) -> StructuredFailure | None:
        """Return a contract failure when active todo checklist items remain open."""

        code_files = [path for path in context.changed_files() if is_reviewable_code_path(Path(path))]
        if not code_files:
            return None

        task = active_task(context.repo_root)
        if not task or task.ambiguous_reason:
            return None

        try:
            todo_text = task.todo_path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            return None

        open_items = self._open_items(todo_text)
        if not open_items:
            return None

        preview = "; ".join(open_items[:3])
        suffix = f" 等 {len(open_items)} 项" if len(open_items) > 3 else ""
        todo_rel = task.todo_path.relative_to(context.repo_root).as_posix()
        return StructuredFailure(
            "ContractGate",
            f"{task.slug} active todo 仍有未完成 checklist: {preview}{suffix}。",
            f"先完成、跳过并说明原因，或标记 blocker；更新 {todo_rel} 后再 final。未完成项存在时不得把任务描述为完成。",
            "contract_failure",
            context.run_id,
        )

    def _open_items(self, text: str) -> list[str]:
        """Markdown checklist item labels that are still unchecked."""

        return [match.group(1).strip(" `") for line in text.splitlines() if (match := self._OPEN_CHECKBOX_PATTERN.match(line))]


class ReviewGate:
    """Stop gate that requires review evidence after code changes."""

    def run(self, context: HookContext) -> StructuredFailure | None:
        """Create or enforce a review request for the active todo."""

        code_files = [path for path in context.changed_files() if is_reviewable_code_path(Path(path))]
        if not code_files:
            return None
        task = active_task(context.repo_root)
        if task and task.ambiguous_reason:
            return StructuredFailure(
                "ReviewGate",
                task.ambiguous_reason,
                "拆分当前 diff，或在 tasks/loops/active.json 中保留唯一匹配的 owned_paths/task_id 后再完成。",
                "ambiguous_task",
                context.run_id,
            )
        if not task:
            tasks_dir = context.repo_root / "tasks"
            todos = sorted(tasks_dir.glob("todo+*.md")) if tasks_dir.is_dir() else []
            if todos:
                return StructuredFailure(
                    "ReviewGate",
                    f"ambiguous_task: 存在 {len(todos)} 个 todo 候选，但没有 active loop state，无法安全绑定当前代码 diff。",
                    "先明确当前任务：保留一个 active todo，或运行/恢复对应 tasks/loops/<slug>/state.json 后再完成。",
                    "ambiguous_task",
                    context.run_id,
                )
            return None

        slug = task.slug
        todo_path = task.todo_path
        review_path = task.review_path or context.repo_root / "tasks" / "reviews" / f"{slug}.md"
        status = review_status(review_path)
        review_doc = parse_review_file(review_path)
        if review_doc.invalid_reason and review_doc.invalid_reason not in {"missing"}:
            return StructuredFailure(
                "ReviewGate",
                f"{slug} review 状态不可用: {review_doc.invalid_reason}。",
                f"运行 `python .codex/skills/apex-init-project-hooks/scripts/apex_loop.py migrate-reviews --repo-root .` 或给 {review_path.relative_to(context.repo_root).as_posix()} 添加结构化 YAML frontmatter。",
                "quality_gate",
                context.run_id,
            )
        if status == "ready":
            validation = validation_status(review_path)
            if validation in {"pass", "automated-pass"}:
                if review_doc.open_blockers:
                    return StructuredFailure(
                        "ReviewGate",
                        f"{slug} review frontmatter 仍有开放 blocker，或 reviewer.role 不满足 risk_level={review_doc.risk_level} 的要求。",
                        f"修正 {review_path.relative_to(context.repo_root).as_posix()} 的 findings/reviewer.role；普通风险用 human、independent-agent 或 ci，高风险用 human 或 ci。",
                        "quality_gate",
                        context.run_id,
                    )
                if not review_doc.required_checks_ok:
                    return StructuredFailure(
                        "ValidationGate",
                        f"{slug} validation 为 pass，但 required_checks 未全部记录 exit_code=0。",
                        f"在 {review_path.relative_to(context.repo_root).as_posix()} 的 frontmatter 中记录实际验证命令和 exit_code=0。",
                        "missing_artifact",
                        context.run_id,
                    )
                if review_covers_current_code(context.repo_root, slug, review_path, code_files):
                    return None
                attempts = update_loop_state(context.repo_root, slug, todo_path, review_path, code_files, context.run_id)
                return StructuredFailure(
                    "ReviewGate",
                    f"{slug} review 已 Ready 且验证通过，但当前代码 diff 和已审查快照不一致。",
                    f"重新审查当前 diff，并更新 {review_path.relative_to(context.repo_root).as_posix()} frontmatter 的 reviewed_file_hashes、status 和 validation。当前尝试次数: {attempts}。",
                    "quality_gate",
                    context.run_id,
                )
            return StructuredFailure(
                "ValidationGate",
                f"{slug} review 已 Ready，但缺少通过的验证证据。" if validation == "missing" else f"{slug} review 已 Ready，但验证状态为 {validation}。",
                f"运行必要验证，并在 {review_path.relative_to(context.repo_root).as_posix()} frontmatter 写入 validation=pass 与 required_checks exit_code=0。",
                "missing_artifact" if validation == "missing" else "quality_gate",
                context.run_id,
            )

        attempts = update_loop_state(context.repo_root, slug, todo_path, review_path, code_files, context.run_id)
        if status == "missing":
            write_review_request(context.repo_root, slug, todo_path, review_path, code_files, context.run_id)
            mark_review_request_created(context.repo_root, slug, review_path)
        reason = self._reason(slug, status, attempts)
        return StructuredFailure(
            "ReviewGate",
            reason,
            f"审查并更新 {review_path.relative_to(context.repo_root).as_posix()} frontmatter；通过时设置 status=ready、validation=pass，并记录 required_checks exit_code=0。",
            "missing_artifact" if status == "missing" else "quality_gate",
            context.run_id,
        )

    def _reason(self, slug: str, status: str, attempts: int) -> str:
        """Block reason based on review state."""

        if attempts >= 3:
            return f"{slug} review gate 连续阻塞 {attempts} 次，需要人工介入或明确降级。"
        if status == "issues":
            return f"{slug} review 文件仍包含 Critical / Warning / blocker 信号，或 reviewer.role 不满足 risk_level 要求。"
        return f"{slug} 有代码 diff，但还没有通过 code-reviewer review。"


class SessionContextBuilder:
    """SessionStart additional context builder."""

    def build(self, context: HookContext) -> str:
        """Return concise session context."""

        lines = ["# Apex Loop Context"]
        branch = context.git(["branch", "--show-current"])
        if branch.returncode == 0 and branch.stdout.strip():
            lines.append(f"- Branch: {branch.stdout.strip()}")
        changed_files = context.changed_files()
        lines.append(f"- Changed files: {len(changed_files)}")

        workflow = resolve_workflow_state(context.repo_root, changed_files)
        lines.append(f"- Workflow state: {workflow.status}")
        if workflow.body:
            first_line = workflow.body.splitlines()[0].strip()
            if first_line:
                lines.append(f"  - {first_line}")

        tasks_dir = context.repo_root / "tasks"
        todos = sorted(tasks_dir.glob("todo+*.md")) if tasks_dir.is_dir() else []
        if todos:
            lines.append("- Active todo candidates:")
            for todo in sorted(todos, key=lambda item: item.stat().st_mtime, reverse=True)[:3]:
                lines.append(f"  - {todo.relative_to(context.repo_root).as_posix()}")

        unresolved = unresolved_reviews(context.repo_root)
        if unresolved:
            lines.append("- Review attention:")
            lines.extend(f"  - {item}" for item in unresolved[:3])

        lessons = recent_lessons(context.repo_root)
        if lessons:
            lines.append("- Recent lessons:")
            lines.extend(f"  - {item}" for item in lessons[:3])
        return "\n".join(lines)


class ApexLoopRuntime:
    """Command dispatcher for Apex hook events."""

    def __init__(self) -> None:
        """Guard composition."""

        self._security = SecurityGuard()
        self._secret_content = SecretContentGuard()
        self._line_lengths = LineLengthGuard()
        self._mirror_drift = MirrorDriftGuard()
        self._contract_gate = ContractGate()
        self._review_gate = ReviewGate()
        self._session_context = SessionContextBuilder()

    def session_start(self, context: HookContext) -> int:
        """Emit additional context for a new session."""

        payload = {"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": self._session_context.build(context)}}
        print(json.dumps(payload, ensure_ascii=False))
        return 0

    def user_prompt_submit(self, context: HookContext) -> int:
        """Emit advisory route hints only."""

        print(workflow_state_context(context.repo_root, context.changed_files()))
        hint = prompt_hint(context.hook_input.prompt_text())
        if hint:
            print(f"[ApexLoopRoute] {hint}")
        return 0

    def pre_tool_use(self, context: HookContext) -> int:
        """Run safety checks before tool execution."""

        failure = self._security.run(context)
        if not failure:
            return 0
        context.write_failure(failure)
        print(
            json.dumps(
                {
                    "hookSpecificOutput": {
                        "hookEventName": "PreToolUse",
                        "permissionDecision": "deny",
                        "permissionDecisionReason": failure.message(),
                    }
                },
                ensure_ascii=False,
            )
        )
        return 2

    def post_tool_use(self, context: HookContext) -> int:
        """Run lightweight checks on files reported by the edit hook."""

        paths = context_paths_diff_aware(context, fallback_to_changed=True)
        secret_failure = self._secret_content.check(context, paths) if paths else None
        if secret_failure:
            mark_security_required(context.repo_root, secret_failure, context.run_id)
            return emit_failure(context, secret_failure)
        findings = self._line_lengths.check(context, paths, block_hard_limit=False) if paths else []
        findings.extend(self._mirror_drift.check(context, block=False))
        for finding in findings:
            emit_warning_or_log(context, finding)
        return 0

    def pre_compact(self, context: HookContext) -> int:
        """Persist compact-safe loop context before host compaction."""

        snapshot_path = context.write_session_snapshot()
        rel_path = snapshot_path.relative_to(context.repo_root).as_posix()
        payload = {
            "hookSpecificOutput": {
                "hookEventName": "PreCompact",
                "additionalContext": f"Apex session snapshot saved at {rel_path}. Restore workflow/review status from this file after compaction.",
            }
        }
        print(json.dumps(payload, ensure_ascii=False))
        return 0

    def stop(self, context: HookContext) -> int:
        """Run completion gates."""

        task = active_task(context.repo_root)
        slug = task.slug if task and not task.ambiguous_reason else "session"
        if context.hook_input.payload.get("stop_hook_active") is True:
            diff_hash = context.current_diff_hash(context.changed_files())
            security_failure = security_required_failure(context.repo_root, context.run_id)
            if security_failure:
                record_stop_blocker(context.repo_root, slug, security_failure, diff_hash, stop_hook_active=True)
            else:
                drift = [finding for finding in self._mirror_drift.check(context, block=True) if finding.action == "block"]
                if drift:
                    record_stop_blocker(context.repo_root, slug, drift[0], diff_hash, stop_hook_active=True)
                else:
                    changed_paths = [Path(path) for path in context.changed_files()]
                    line_blockers = [finding for finding in self._line_lengths.check(context, changed_paths, block_hard_limit=True) if finding.action == "block"]
                    if line_blockers:
                        record_stop_blocker(context.repo_root, slug, line_blockers[0], diff_hash, stop_hook_active=True)
                    else:
                        record_active_stop_continuation(context.repo_root, slug)
            message = active_stop_blocker_message(context.repo_root, slug)
            if message:
                print(json.dumps({"decision": "allow", "status": "blocked", "reason": message}, ensure_ascii=False))
            return 0
        diff_hash = context.current_diff_hash(context.changed_files())
        security_failure = security_required_failure(context.repo_root, context.run_id)
        if security_failure:
            record_stop_blocker(context.repo_root, slug, security_failure, diff_hash)
            return emit_failure(context, security_failure, stop_decision=True)
        drift = [finding for finding in self._mirror_drift.check(context, block=True) if finding.action == "block"]
        if drift:
            record_stop_blocker(context.repo_root, slug, drift[0], diff_hash)
            return emit_failure(context, drift[0], stop_decision=True)
        changed_paths = [Path(path) for path in context.changed_files()]
        line_blockers = [finding for finding in self._line_lengths.check(context, changed_paths, block_hard_limit=True) if finding.action == "block"]
        if line_blockers:
            record_stop_blocker(context.repo_root, slug, line_blockers[0], diff_hash)
            return emit_failure(context, line_blockers[0], stop_decision=True)
        contract_failure = self._contract_gate.run(context)
        if contract_failure:
            record_stop_blocker(context.repo_root, slug, contract_failure, diff_hash)
            return emit_failure(context, contract_failure, stop_decision=True)
        failure = self._review_gate.run(context)
        if failure:
            record_stop_blocker(context.repo_root, slug, failure, diff_hash)
            return emit_failure(context, failure, stop_decision=True)
        if task and not task.ambiguous_reason:
            reset_stop_blocker(context.repo_root, task.slug)
        return 0

    def check_line_length(self, context: HookContext, paths: list[str]) -> int:
        """Manual line-length check command."""

        rel_paths = [context.rel_path(path) for path in paths] if paths else [Path(path) for path in context.changed_files()]
        findings = self._line_lengths.check(context, [path for path in rel_paths if path], block_hard_limit=True)
        for finding in findings:
            emit_warning_or_log(context, finding)
        return 2 if any(finding.action == "block" for finding in findings) else 0

    def check_agent_mirrors(self, context: HookContext) -> int:
        """Manual mirror drift check command."""

        findings = self._mirror_drift.check(context, block=True)
        for finding in findings:
            emit_warning_or_log(context, finding)
        return 2 if findings else 0

    def migrate_reviews(self, context: HookContext) -> int:
        """Migrate legacy review files to structured frontmatter."""

        changed = migrate_reviews(context.repo_root)
        print(json.dumps({"migrated": changed}, ensure_ascii=False, indent=2))
        return 0


def prompt_hint(prompt: str) -> str:
    """Advisory route hint from prompt text."""

    text = prompt.lower()
    if not text:
        return ""
    if any(token in text for token in ("review", "审查", "验收", "检查")):
        return "检测到 review / 验收意图；优先读取 active todo、diff 和 tasks/reviews，再调用 code-reviewer。"
    if any(token in text for token in ("plan", "计划", "方案", "todo")):
        return "检测到 planning 意图；可以先写 tasks/todo+任务名.md，确认范围后再实现。"
    if any(token in text for token in ("完成", "收工", "done", "提交")):
        return "检测到完成意图；Stop gate 会检查 diff、review 和验证证据。"
    return ""


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""

    parser = argparse.ArgumentParser(description="ApexPowers loop hook runtime.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    hook_commands = [
        "session-start",
        "user-prompt-submit",
        "pre-tool-use",
        "post-tool-use",
        "post-tool-batch",
        "pre-compact",
        "stop",
        "task-completed",
        "check-agent-mirrors",
        "migrate-reviews",
    ]
    for command in hook_commands:
        subparser = subparsers.add_parser(command)
        add_common_hook_args(subparser)
    line_parser = subparsers.add_parser("check-line-length")
    add_common_hook_args(line_parser)
    line_parser.add_argument("paths", nargs="*")
    render_parser = subparsers.add_parser("render-config")
    render_parser.add_argument("render_host", choices=["codex", "claude"])
    render_parser.add_argument("--script-path", required=True)
    render_parser.add_argument("--config-format", choices=["json", "toml"], default="json")
    return parser.parse_args()


def add_common_hook_args(parser: argparse.ArgumentParser) -> None:
    """Add hook command flags."""

    parser.add_argument("--host", choices=["codex", "claude"], default="codex")
    parser.add_argument("--route", default="default")
    parser.add_argument("--repo-root")


def main() -> int:
    """CLI entrypoint."""

    args = parse_args()
    if args.command == "render-config":
        renderer = HostConfigRenderer(RouteRegistry())
        if args.config_format == "toml":
            if args.render_host != "codex":
                raise SystemExit("TOML hook config rendering is only supported for Codex.")
            print(renderer.render_toml(args.render_host, args.script_path), end="")
        else:
            print(renderer.render_json(args.render_host, args.script_path), end="")
        return 0

    runtime = ApexLoopRuntime()
    context = HookContext.create(args)
    dispatch = {
        "session-start": runtime.session_start,
        "user-prompt-submit": runtime.user_prompt_submit,
        "pre-tool-use": runtime.pre_tool_use,
        "post-tool-use": runtime.post_tool_use,
        "post-tool-batch": runtime.post_tool_use,
        "pre-compact": runtime.pre_compact,
        "stop": runtime.stop,
        "task-completed": runtime.stop,
        "check-agent-mirrors": runtime.check_agent_mirrors,
        "migrate-reviews": runtime.migrate_reviews,
    }
    if args.command == "check-line-length":
        return runtime.check_line_length(context, args.paths)
    return dispatch[args.command](context)
