"""Guard implementations and CLI dispatcher for Apex loop hooks."""

from __future__ import annotations

# Runtime copy marker: Generated by ApexPowers apex-init-project-hooks.

import argparse
import json
import re
from pathlib import Path

from apex_loop_routes import HostConfigRenderer, RouteRegistry, StructuredFailure
from apex_loop_utils import (
    HookContext,
    context_paths_or_changed,
    count_effective_lines,
    emit_failure,
    emit_warning_or_log,
    is_generated_exception,
    is_reviewable_code_path,
    is_secret_path,
    is_source_file,
    newest_todo,
    recent_lessons,
    review_covers_current_code,
    resolve_workflow_state,
    review_status,
    safe_slug,
    thresholds_for,
    unresolved_reviews,
    update_loop_state,
    validation_status,
    workflow_state_context,
    write_review_request,
)


class SecurityGuard:
    """PreToolUse safety checks for commands and secret paths."""

    _dangerous_patterns = [
        (re.compile(r"\brm\s+-rf\s+(/|~|\$HOME|%USERPROFILE%|[A-Za-z]:\\?)", re.I), "危险递归删除"),
        (re.compile(r"\bgit\s+reset\s+--hard\b", re.I), "破坏性 git reset"),
        (re.compile(r"\bgit\s+checkout\s+--\b", re.I), "破坏性 git checkout"),
        (re.compile(r"\bgit\s+push\b.*\s--force", re.I), "force push"),
        (re.compile(r"(curl|wget|Invoke-WebRequest|iwr)\b.*(\||;).*(bash|sh|iex|Invoke-Expression)", re.I), "远程脚本管道执行"),
        (re.compile(r"\b(eval|Invoke-Expression|iex)\b", re.I), "动态执行字符串"),
    ]

    def run(self, context: HookContext) -> StructuredFailure | None:
        """Return the first blocking security failure."""

        command = context.hook_input.command_text()
        for pattern, label in self._dangerous_patterns:
            if command and pattern.search(command):
                return StructuredFailure(
                    "SecurityGuard",
                    f"{label}: {command[:180]}",
                    "让用户明确授权并说明风险，或改用更小范围、可逆的命令。",
                    "security_risk",
                    context.run_id,
                )

        for path_text in context.hook_input.file_paths():
            rel_path = context.rel_path(path_text)
            if rel_path and is_secret_path(rel_path):
                return StructuredFailure(
                    "SecretPathGuard",
                    f"疑似 secrets 路径被访问: {rel_path.as_posix()}",
                    "不要读取或写入 secrets；改用 .env.example、占位变量或让用户手动处理。",
                    "security_risk",
                    context.run_id,
                )
        return None


class LineLengthGuard:
    """PostToolUse file size checks using effective code lines."""

    def check(self, context: HookContext, paths: list[Path]) -> list[StructuredFailure]:
        """Check changed source files and return warnings or blocks."""

        findings: list[StructuredFailure] = []
        for rel_path in paths:
            if not is_source_file(rel_path) or is_generated_exception(rel_path):
                continue
            absolute = context.absolute(rel_path)
            if not absolute.is_file():
                continue
            lines = count_effective_lines(absolute)
            warning, hard, target = thresholds_for(rel_path)
            if lines > hard:
                findings.append(
                    StructuredFailure(
                        "LineLengthGuard",
                        f"{rel_path.as_posix()} 有效代码行 {lines}，超过硬上限 {hard}。",
                        f"拆分到子模块、helper、types、constants 或组件；目标区间 {target}。",
                        "quality_gate",
                        context.run_id,
                    )
                )
            elif lines > warning:
                findings.append(
                    StructuredFailure(
                        "LineLengthGuard",
                        f"{rel_path.as_posix()} 有效代码行 {lines}，超过强提醒线 {warning}。",
                        f"评估拆分；目标区间 {target}，超过 {hard} 会阻塞。",
                        "quality_gate",
                        context.run_id,
                        action="warn",
                    )
                )
        return findings


class SecretContentGuard:
    """PostToolUse scan for accidentally written credentials."""

    _secret_patterns = [
        re.compile(r"-----BEGIN (OPENSSH|RSA|DSA|EC) PRIVATE KEY-----"),
        re.compile(r"\bsk-[A-Za-z0-9_-]{20,}\b"),
        re.compile(r"\bghp_[A-Za-z0-9_]{20,}\b"),
        re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
        re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{20,}\b"),
    ]

    def check(self, context: HookContext, paths: list[Path]) -> StructuredFailure | None:
        """Return a blocking finding when changed content looks secret-like."""

        for rel_path in paths:
            absolute = context.absolute(rel_path)
            if not absolute.is_file() or is_secret_path(rel_path):
                continue
            try:
                text = absolute.read_text(encoding="utf-8", errors="ignore")[:200_000]
            except OSError:
                continue
            if any(pattern.search(text) for pattern in self._secret_patterns):
                return StructuredFailure(
                    "SecretContentGuard",
                    f"{rel_path.as_posix()} 疑似包含 token、API key 或 private key。",
                    "移除真实密钥，改用占位符、环境变量名或 .env.example。",
                    "security_risk",
                    context.run_id,
                )
        return None


class MirrorDriftGuard:
    """Detect source agent changes without generated mirror changes."""

    def check(self, context: HookContext, block: bool) -> list[StructuredFailure]:
        """Return mirror drift findings."""

        changed = set(context.changed_files())
        findings: list[StructuredFailure] = []
        for source in sorted(path for path in changed if path.startswith(".agents/") and path.endswith(".md")):
            name = Path(source).stem
            if name.lower() == "agents":
                continue
            expected = {f".codex/agents/{name}.toml", f".claude/agents/{name}.md"}
            missing = sorted(expected - changed)
            if missing:
                findings.append(
                    StructuredFailure(
                        "MirrorDriftGuard",
                        f"{source} 已变化，但镜像未同步: {', '.join(missing)}",
                        "运行 python .codex\\skills\\apex-sync-agent-mirrors\\scripts\\sync_agent_mirrors.py . --target all --write",
                        "missing_artifact",
                        context.run_id,
                        action="block" if block else "warn",
                    )
                )
        return findings


class ReviewGate:
    """Stop gate that requires review evidence after code changes."""

    def run(self, context: HookContext) -> StructuredFailure | None:
        """Create or enforce a review request for the active todo."""

        code_files = [path for path in context.changed_files() if is_reviewable_code_path(Path(path))]
        if not code_files:
            return None
        todo_path = newest_todo(context.repo_root)
        if not todo_path:
            return None

        slug = safe_slug(todo_path.stem.removeprefix("todo+"), "task")
        review_path = context.repo_root / "tasks" / "reviews" / f"{slug}.md"
        status = review_status(review_path)
        if status == "ready":
            validation = validation_status(review_path)
            if validation == "pass":
                if review_covers_current_code(context.repo_root, slug, review_path, code_files):
                    return None
                attempts = update_loop_state(context.repo_root, slug, todo_path, review_path, code_files, context.run_id)
                return StructuredFailure(
                    "ReviewGate",
                    f"{slug} review 已 Ready 且验证通过，但当前代码 diff 和已审查快照不一致。",
                    f"重新审查当前 diff，并更新 {review_path.relative_to(context.repo_root).as_posix()}；通过后再次写入 `> **Status**: Ready` 和 `> **Validation**: Pass`。当前尝试次数: {attempts}。",
                    "quality_gate",
                    context.run_id,
                )
            return StructuredFailure(
                "ValidationGate",
                f"{slug} review 已 Ready，但缺少通过的验证证据。" if validation == "missing" else f"{slug} review 已 Ready，但验证状态为 {validation}。",
                f"运行必要的 lint/type-check/test，并在 {review_path.relative_to(context.repo_root).as_posix()} 写入 `> **Validation**: Pass` 和命令结果摘要。",
                "missing_artifact" if validation == "missing" else "quality_gate",
                context.run_id,
            )

        attempts = update_loop_state(context.repo_root, slug, todo_path, review_path, code_files, context.run_id)
        if status == "missing":
            write_review_request(context.repo_root, slug, todo_path, review_path, code_files, context.run_id)
        reason = self._reason(slug, status, attempts)
        return StructuredFailure(
            "ReviewGate",
            reason,
            f"审查并更新 {review_path.relative_to(context.repo_root).as_posix()}，通过时写入 `> **Status**: Ready` 和 `> **Validation**: Pass`。",
            "missing_artifact" if status == "missing" else "quality_gate",
            context.run_id,
        )

    def _reason(self, slug: str, status: str, attempts: int) -> str:
        """Block reason based on review state."""

        if attempts >= 3:
            return f"{slug} review gate 连续阻塞 {attempts} 次，需要人工介入或明确降级。"
        if status == "issues":
            return f"{slug} review 文件仍包含 Critical / Warning / blocker 信号。"
        return f"{slug} 有代码 diff，但还没有通过 code-reviewer review。"


class SessionContextBuilder:
    """SessionStart additional context builder."""

    def build(self, context: HookContext) -> str:
        """Return concise session context."""

        lines = ["# Apex Loop Context"]
        branch = context.git(["branch", "--show-current"])
        if branch.returncode == 0 and branch.stdout.strip():
            lines.append(f"- Branch: {branch.stdout.strip()}")
        changed_files = context.changed_files()
        lines.append(f"- Changed files: {len(changed_files)}")

        workflow = resolve_workflow_state(context.repo_root, changed_files)
        lines.append(f"- Workflow state: {workflow.status}")
        if workflow.body:
            first_line = workflow.body.splitlines()[0].strip()
            if first_line:
                lines.append(f"  - {first_line}")

        tasks_dir = context.repo_root / "tasks"
        todos = sorted(tasks_dir.glob("todo+*.md")) if tasks_dir.is_dir() else []
        if todos:
            lines.append("- Active todo candidates:")
            for todo in sorted(todos, key=lambda item: item.stat().st_mtime, reverse=True)[:3]:
                lines.append(f"  - {todo.relative_to(context.repo_root).as_posix()}")

        unresolved = unresolved_reviews(context.repo_root)
        if unresolved:
            lines.append("- Review attention:")
            lines.extend(f"  - {item}" for item in unresolved[:3])

        lessons = recent_lessons(context.repo_root)
        if lessons:
            lines.append("- Recent lessons:")
            lines.extend(f"  - {item}" for item in lessons[:3])
        return "\n".join(lines)


class ApexLoopRuntime:
    """Command dispatcher for Apex hook events."""

    def __init__(self) -> None:
        """Guard composition."""

        self._security = SecurityGuard()
        self._secret_content = SecretContentGuard()
        self._line_lengths = LineLengthGuard()
        self._mirror_drift = MirrorDriftGuard()
        self._review_gate = ReviewGate()
        self._session_context = SessionContextBuilder()

    def session_start(self, context: HookContext) -> int:
        """Emit additional context for a new session."""

        payload = {"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": self._session_context.build(context)}}
        print(json.dumps(payload, ensure_ascii=False))
        return 0

    def user_prompt_submit(self, context: HookContext) -> int:
        """Emit advisory route hints only."""

        print(workflow_state_context(context.repo_root, context.changed_files()))
        hint = prompt_hint(context.hook_input.prompt_text())
        if hint:
            print(f"[ApexLoopRoute] {hint}")
        return 0

    def pre_tool_use(self, context: HookContext) -> int:
        """Run safety checks before tool execution."""

        failure = self._security.run(context)
        return emit_failure(context, failure) if failure else 0

    def post_tool_use(self, context: HookContext) -> int:
        """Run edit checks and advisory observers after tool execution."""

        paths = context_paths_or_changed(context)
        secret_failure = self._secret_content.check(context, paths)
        if secret_failure:
            return emit_failure(context, secret_failure)
        findings = self._line_lengths.check(context, paths)
        findings.extend(self._mirror_drift.check(context, block=False))
        for finding in findings:
            emit_warning_or_log(context, finding)
        blockers = [finding for finding in findings if finding.action == "block"]
        return emit_failure(context, blockers[0]) if blockers else 0

    def stop(self, context: HookContext) -> int:
        """Run completion gates."""

        drift = [finding for finding in self._mirror_drift.check(context, block=True) if finding.action == "block"]
        if drift:
            return emit_failure(context, drift[0], stop_decision=True)
        failure = self._review_gate.run(context)
        return emit_failure(context, failure, stop_decision=True) if failure else 0

    def check_line_length(self, context: HookContext, paths: list[str]) -> int:
        """Manual line-length check command."""

        rel_paths = [context.rel_path(path) for path in paths] if paths else [Path(path) for path in context.changed_files()]
        findings = self._line_lengths.check(context, [path for path in rel_paths if path])
        for finding in findings:
            emit_warning_or_log(context, finding)
        return 2 if any(finding.action == "block" for finding in findings) else 0

    def check_agent_mirrors(self, context: HookContext) -> int:
        """Manual mirror drift check command."""

        findings = self._mirror_drift.check(context, block=True)
        for finding in findings:
            emit_warning_or_log(context, finding)
        return 2 if findings else 0


def prompt_hint(prompt: str) -> str:
    """Advisory route hint from prompt text."""

    text = prompt.lower()
    if not text:
        return ""
    if any(token in text for token in ("review", "审查", "验收", "检查")):
        return "检测到 review / 验收意图；优先读取 active todo、diff 和 tasks/reviews，再调用 code-reviewer。"
    if any(token in text for token in ("plan", "计划", "方案", "todo")):
        return "检测到 planning 意图；可以先写 tasks/todo+任务名.md，确认范围后再实现。"
    if any(token in text for token in ("完成", "收工", "done", "提交")):
        return "检测到完成意图；Stop gate 会检查 diff、review 和验证证据。"
    return ""


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""

    parser = argparse.ArgumentParser(description="ApexPowers loop hook runtime.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    hook_commands = ["session-start", "user-prompt-submit", "pre-tool-use", "post-tool-use", "stop", "task-completed", "check-agent-mirrors"]
    for command in hook_commands:
        subparser = subparsers.add_parser(command)
        add_common_hook_args(subparser)
    line_parser = subparsers.add_parser("check-line-length")
    add_common_hook_args(line_parser)
    line_parser.add_argument("paths", nargs="*")
    render_parser = subparsers.add_parser("render-config")
    render_parser.add_argument("render_host", choices=["codex", "claude"])
    render_parser.add_argument("--script-path", required=True)
    return parser.parse_args()


def add_common_hook_args(parser: argparse.ArgumentParser) -> None:
    """Add hook command flags."""

    parser.add_argument("--host", choices=["codex", "claude"], default="codex")
    parser.add_argument("--route", default="default")
    parser.add_argument("--repo-root")


def main() -> int:
    """CLI entrypoint."""

    args = parse_args()
    if args.command == "render-config":
        print(HostConfigRenderer(RouteRegistry()).render(args.render_host, args.script_path), end="")
        return 0

    runtime = ApexLoopRuntime()
    context = HookContext.create(args)
    dispatch = {
        "session-start": runtime.session_start,
        "user-prompt-submit": runtime.user_prompt_submit,
        "pre-tool-use": runtime.pre_tool_use,
        "post-tool-use": runtime.post_tool_use,
        "stop": runtime.stop,
        "task-completed": runtime.stop,
        "check-agent-mirrors": runtime.check_agent_mirrors,
    }
    if args.command == "check-line-length":
        return runtime.check_line_length(context, args.paths)
    return dispatch[args.command](context)
