#!/usr/bin/env python3
"""Command entrypoint for ApexPowers loop hooks."""

from __future__ import annotations

# Runtime copy marker: Generated by ApexPowers apex-init-project-hooks.

import sys
from pathlib import Path


sys.path.insert(0, str(Path(__file__).resolve().parent))

from apex_loop_core import main  # noqa: E402


if __name__ == "__main__":
    raise SystemExit(main())
