#!/usr/bin/env python3
"""Install ApexPowers loop hooks into a target project."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 fallback.
    tomllib = None  # type: ignore[assignment]


GENERATED_MARKER = "Generated by ApexPowers apex-init-project-hooks"
MANIFEST_VERSION = 1
PROJECT_MANIFEST_PATH = "tasks/loops/.apex-manifest.json"
HOST_MANIFEST_PATH = "apex/manifest.json"
TOML_BEGIN_MARKER = f"# >>> apex-managed-hooks-begin ({GENERATED_MARKER}) >>>"
TOML_END_MARKER = "# <<< apex-managed-hooks-end <<<"
TOML_BLOCK_PATTERN = re.compile(
    r"(?ms)^# >>> apex-managed-hooks-begin \(Generated by ApexPowers apex-init-project-hooks\) >>>\n.*?^# <<< apex-managed-hooks-end <<<\n?"
)


@dataclass(frozen=True)
class PlannedWrite:
    """A file that may be written by the installer."""

    path: Path
    content: str
    binary: bool = False
    merge_json: bool = False
    merge_toml: bool = False
    manifest_root: str = "project"
    managed_kind: str = "file"
    protected: bool = False
    overwrite_generated: bool = True
    track_manifest: bool = True


@dataclass(frozen=True)
class PlannedCleanup:
    """A legacy project-local hook file that may be migrated away."""

    path: Path
    cleanup_type: str


@dataclass(frozen=True)
class PlannedDirectory:
    """A directory that should exist after installation."""

    path: Path


@dataclass(frozen=True)
class PlanResult:
    """Installer action result."""

    path: Path
    action: str
    kind: str


@dataclass(frozen=True)
class WriteDecision:
    """Resolved write decision for one planned file."""

    should_write: bool
    action: str
    content: str


@dataclass(frozen=True)
class CleanupDecision:
    """Resolved cleanup decision for one legacy file."""

    action: str
    content: str | None = None


@dataclass(frozen=True)
class ManifestEntry:
    """One Apex-managed file recorded for update and uninstall safety."""

    path: Path
    root: str
    relative_path: str
    kind: str
    content_hash: str
    protected: bool = False


@dataclass(frozen=True)
class ManifestRecord:
    """Loaded manifest entry with provenance."""

    entry: ManifestEntry
    manifest_path: Path


@dataclass(frozen=True)
class UninstallDecision:
    """Resolved uninstall decision for one manifest entry."""

    action: str
    content: str | None = None


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""

    parser = argparse.ArgumentParser(description="Install ApexPowers loop hooks into an existing project.")
    parser.add_argument("root", nargs="?", default=".", help="Project root. Defaults to current directory.")
    parser.add_argument(
        "--hook-scope",
        choices=["agent", "project"],
        default="agent",
        help="Install hook config/runtime into agent homes by default; use project for legacy project-local hooks.",
    )
    parser.add_argument("--codex-home", help="Codex agent root. Defaults to CODEX_HOME or ~/.codex.")
    parser.add_argument("--claude-home", help="Claude Code agent root. Defaults to CLAUDE_HOME or ~/.claude.")
    parser.add_argument(
        "--codex-config-format",
        choices=["auto", "toml", "json"],
        default="auto",
        help="Codex hook config format. Auto uses config.toml for agent scope and hooks.json for legacy project scope.",
    )
    parser.add_argument("--write", action="store_true", help="Write files. Default is dry-run.")
    parser.add_argument("--update", action="store_true", help="Reapply managed hook files using manifest-aware safety checks.")
    parser.add_argument("--uninstall", action="store_true", help="Remove Apex-managed hook files recorded in manifests.")
    parser.add_argument(
        "--force",
        "--regenerate",
        action="store_true",
        dest="force",
        help="Overwrite existing generated files and hand-written hook files.",
    )
    parser.add_argument("--json", action="store_true", help="Output machine-readable JSON.")
    args = parser.parse_args()
    if args.update and args.uninstall:
        parser.error("--update and --uninstall cannot be used together.")
    return args


def default_agent_home(env_name: str, dirname: str) -> Path:
    """Default agent root from environment or user home."""

    value = Path.home() / dirname
    if env_name in os.environ:
        value = Path(os.environ[env_name])
    return value.expanduser().resolve()


def get_agent_home(host: str) -> Path:
    """Resolve the default agent home for a host without hard-coded user paths."""

    if os.environ.get("AGENT_HOME"):
        return Path(os.environ["AGENT_HOME"]).expanduser().resolve()
    if host == "codex":
        return default_agent_home("CODEX_HOME", ".codex")
    if host == "claude":
        return default_agent_home("CLAUDE_HOME", ".claude")
    raise ValueError(f"Unsupported host: {host}")


def resolve_base(path_value: str | None, fallback: Path) -> Path:
    """Resolve an optional root path."""

    return (Path(path_value) if path_value else fallback).expanduser().resolve()


def resolve_inside(root: Path, path_value: str, label: str) -> Path:
    """Resolve a path and keep it inside the selected root."""

    candidate = Path(path_value)
    if not candidate.is_absolute():
        candidate = root / candidate
    resolved = candidate.resolve()
    try:
        resolved.relative_to(root)
    except ValueError as exc:
        raise SystemExit(f"{label} must stay inside project root: {resolved}") from exc
    return resolved


def source_relative_path(path: Path, root: Path) -> str:
    """Path relative to project root when possible."""

    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def normalize_text(content: str) -> str:
    """Text normalized for cross-platform hashing."""

    return content.replace("\r\n", "\n").replace("\r", "\n")


def content_hash(content: str) -> str:
    """SHA-256 hash for normalized text content."""

    return hashlib.sha256(normalize_text(content).encode("utf-8")).hexdigest()


def file_content_hash(path: Path) -> str:
    """SHA-256 hash for a text file using Apex newline normalization."""

    return content_hash(path.read_text(encoding="utf-8", errors="ignore"))


def default_workflow_template() -> str:
    """Default workflow-state contract installed into project loop state."""

    return """# Apex Workflow

This file is intentionally editable. Apex loop hooks read the matching state block and inject it into session context.

[apex-state:no_task]
No active `tasks/todo+*.md` file was found. Answer direct questions normally; when work starts, create or select a todo before implementation.
[/apex-state:no_task]

[apex-state:planning]
An active todo exists, but implementation evidence is still thin. Clarify scope, constraints, acceptance criteria, and expected validation before changing code.
[/apex-state:planning]

[apex-state:implementing]
Implementation is in progress. Keep changes scoped to the active todo, preserve existing user edits, and update loop state as evidence changes.
[/apex-state:implementing]

[apex-state:security_required]
A completed tool produced secret-like content. Remove the content, rotate any real credential, and verify cleanup before attempting completion.
[/apex-state:security_required]

[apex-state:review_required]
Code changes require review. Inspect the diff and active todo, then create or update `tasks/reviews/<slug>.md` with review status.
[/apex-state:review_required]

[apex-state:validation_required]
Review is ready, but validation evidence is incomplete. Run the relevant checks, then set review frontmatter `validation` to `pass` or `automated-pass` and record required check exit codes.
[/apex-state:validation_required]

[apex-state:done]
Review and validation are complete. Summarize the change, mention verification, and leave commit/push decisions to the user unless explicitly requested.
[/apex-state:done]
"""


def load_runtime_module() -> ModuleType:
    """Load apex_loop.py so route registry remains the source of truth."""

    runtime_dir = Path(__file__).parent
    runtime_path = runtime_dir / "apex_loop_core.py"
    if str(runtime_dir) not in sys.path:
        sys.path.insert(0, str(runtime_dir))
    spec = importlib.util.spec_from_file_location("apex_loop_core_dynamic", runtime_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load runtime module: {runtime_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def render_host_config(runtime: ModuleType, host: str, script_path: str, config_format: str = "json") -> str:
    """Render host config from the runtime route registry."""

    renderer = runtime.HostConfigRenderer(runtime.RouteRegistry())
    if config_format == "toml":
        return renderer.render_toml(host, script_path)
    return renderer.render_json(host, script_path)


def command_path(path: Path, base: Path, scope: str) -> str:
    """Runtime script path embedded in host hook config."""

    if scope == "project":
        try:
            return path.relative_to(base).as_posix()
        except ValueError:
            pass
    return path.resolve().as_posix()


def resolve_codex_config_format(codex_home: Path, hook_scope: str, requested: str) -> str:
    """Resolve Codex host config format for an install run."""

    if requested != "auto":
        return requested
    if hook_scope == "project":
        return "json"
    return "toml"


def planned_outputs(
    root: Path,
    codex_home: Path,
    claude_home: Path,
    hook_scope: str,
    codex_config_format: str,
) -> tuple[list[PlannedDirectory], list[PlannedWrite], list[PlannedCleanup]]:
    """Build the installation plan."""

    runtime = load_runtime_module()
    scripts_dir = Path(__file__).parent
    runtime_files = sorted(scripts_dir.glob("apex_loop*.py"))

    codex_base = root / ".codex" if hook_scope == "project" else codex_home
    claude_base = root / ".claude" if hook_scope == "project" else claude_home
    codex_runtime = resolve_inside(codex_base, "hooks/apex_loop.py", "codex-runtime")
    claude_runtime = resolve_inside(claude_base, "hooks/apex_loop.py", "claude-runtime")
    codex_config_name = "config.toml" if codex_config_format == "toml" else "hooks.json"
    codex_config = resolve_inside(codex_base, codex_config_name, "codex-config")
    claude_config = resolve_inside(claude_base, "settings.json", "claude-config")
    lessons = resolve_inside(root, "tasks/lessons.md", "lessons")
    loops_keep = resolve_inside(root, "tasks/loops/.gitkeep", "loops-gitkeep")
    workflow = resolve_inside(root, "tasks/loops/workflow.md", "workflow")
    reviews_keep = resolve_inside(root, "tasks/reviews/.gitkeep", "reviews-gitkeep")
    codex_command_path = command_path(codex_runtime, root, hook_scope)
    claude_command_path = command_path(claude_runtime, root, hook_scope)

    dirs = [
        PlannedDirectory(codex_runtime.parent),
        PlannedDirectory(claude_runtime.parent),
        PlannedDirectory(loops_keep.parent),
        PlannedDirectory(reviews_keep.parent),
        PlannedDirectory(resolve_inside(codex_base, "apex", "codex-manifest-dir")),
        PlannedDirectory(resolve_inside(claude_base, "apex", "claude-manifest-dir")),
    ]
    files = []
    for runtime_file in runtime_files:
        content = runtime_file.read_text(encoding="utf-8")
        files.append(PlannedWrite(codex_runtime.parent / runtime_file.name, content, manifest_root="codex", managed_kind="runtime"))
        files.append(PlannedWrite(claude_runtime.parent / runtime_file.name, content, manifest_root="claude", managed_kind="runtime"))
    files.extend(
        [
            PlannedWrite(
                codex_config,
                render_host_config(runtime, "codex", codex_command_path, codex_config_format),
                merge_json=codex_config_format == "json",
                merge_toml=codex_config_format == "toml",
                manifest_root="codex",
                managed_kind="host-config",
            ),
            PlannedWrite(claude_config, render_host_config(runtime, "claude", claude_command_path), merge_json=True, manifest_root="claude", managed_kind="host-config"),
            PlannedWrite(loops_keep, "", managed_kind="state"),
            PlannedWrite(workflow, default_workflow_template(), managed_kind="workflow", protected=True, overwrite_generated=False),
            PlannedWrite(reviews_keep, "", managed_kind="state"),
            PlannedWrite(lessons, "# Lessons\n\n", managed_kind="lessons", protected=True, overwrite_generated=False),
        ]
    )

    cleanups: list[PlannedCleanup] = []
    if hook_scope == "agent":
        cleanups.extend(
            [
                PlannedCleanup(resolve_inside(root, ".codex/hooks.json", "legacy-codex-config"), "host-config"),
                PlannedCleanup(resolve_inside(root, ".codex/config.toml", "legacy-codex-toml-config"), "host-config"),
                PlannedCleanup(resolve_inside(root, ".claude/settings.json", "legacy-claude-config"), "host-config"),
            ]
        )
        for runtime_file in runtime_files:
            cleanups.append(PlannedCleanup(resolve_inside(root, f".codex/hooks/{runtime_file.name}", "legacy-codex-runtime"), "runtime"))
            cleanups.append(PlannedCleanup(resolve_inside(root, f".claude/hooks/{runtime_file.name}", "legacy-claude-runtime"), "runtime"))

    return dirs, files, cleanups


def should_write(planned: PlannedWrite, force: bool) -> WriteDecision:
    """Return write decision and resolved content."""

    if not planned.path.exists():
        return WriteDecision(True, "create", planned.content)

    existing = planned.path.read_text(encoding="utf-8", errors="ignore")
    if existing == planned.content:
        return WriteDecision(False, "unchanged", planned.content)

    if planned.merge_toml:
        merged = merge_toml_host_config(existing, planned.content)
        if merged:
            if normalize_text(existing) == normalize_text(merged):
                return WriteDecision(False, "unchanged", merged)
            return WriteDecision(True, "merge", merged)
        return WriteDecision(False, "skip-existing", planned.content)

    if planned.merge_json and not force:
        merged = merge_host_config(existing, planned.content)
        if merged:
            if existing == merged:
                return WriteDecision(False, "unchanged", merged)
            return WriteDecision(True, "merge", merged)
        return WriteDecision(False, "skip-existing", planned.content)

    if force or (planned.overwrite_generated and (GENERATED_MARKER in existing or "ApexPowers apex-init-project-hooks" in existing)):
        return WriteDecision(True, "overwrite", planned.content)
    return WriteDecision(False, "skip-existing", planned.content)


def merge_host_config(existing_content: str, managed_content: str) -> str | None:
    """Merge Apex hook entries into an existing host JSON config."""

    try:
        existing = json.loads(existing_content)
        managed = json.loads(managed_content)
    except json.JSONDecodeError:
        return None
    if not isinstance(existing, dict) or not isinstance(managed, dict):
        return None

    cleaned = {
        key: value
        for key, value in existing.items()
        if key not in {"_generated_by", "_generated_marker"}
    }
    existing_hooks = cleaned.get("hooks")
    if not isinstance(existing_hooks, dict):
        existing_hooks = {}
    managed_hooks = managed.get("hooks")
    if not isinstance(managed_hooks, dict):
        return None

    merged_hooks: dict[str, list[object]] = {}
    for event, entries in existing_hooks.items():
        if isinstance(entries, list):
            merged_hooks[str(event)] = [
                entry
                for entry in (strip_apex_hook_entry(entry) for entry in entries)
                if entry is not None
            ]
    for event, entries in managed_hooks.items():
        if not isinstance(entries, list):
            continue
        merged_hooks[str(event)] = [*merged_hooks.get(str(event), []), *entries]
    cleaned["hooks"] = merged_hooks
    return json.dumps(cleaned, ensure_ascii=False, indent=2) + "\n"


def merge_toml_host_config(existing_content: str, managed_content: str) -> str | None:
    """Merge Apex hook entries into a Codex config.toml managed block."""

    stripped, _changed = strip_apex_toml_block(existing_content)
    if not is_valid_toml(stripped):
        return None
    base = normalize_text(stripped).rstrip()
    managed = normalize_text(managed_content).strip() + "\n"
    if not base:
        return managed
    return base + "\n\n" + managed


def strip_apex_toml_block(content: str) -> tuple[str, bool]:
    """Remove Apex-managed TOML blocks while preserving user config."""

    normalized = normalize_text(content)
    stripped, count = TOML_BLOCK_PATTERN.subn("", normalized)
    return stripped.rstrip() + ("\n" if stripped.strip() else ""), count > 0


def is_valid_toml(content: str) -> bool:
    """Validate TOML when the runtime supports tomllib."""

    if not content.strip() or tomllib is None:
        return True
    try:
        tomllib.loads(content)
    except tomllib.TOMLDecodeError:
        return False
    return True


def strip_apex_hook_entry(value: object) -> object | None:
    """Remove only Apex-managed commands from a host hook entry."""

    if not isinstance(value, dict):
        return value
    if is_apex_command(value):
        return None

    cleaned = dict(value)
    hooks = cleaned.get("hooks")
    if isinstance(hooks, list):
        kept = [hook for hook in hooks if not is_apex_hook_entry(hook)]
        if not kept:
            return None
        cleaned["hooks"] = kept
    return cleaned


def is_apex_command(value: object) -> bool:
    """Whether a command object is managed by Apex loop hooks."""

    return isinstance(value, dict) and isinstance(value.get("command"), str) and "apex_loop.py" in value["command"]


def is_apex_hook_entry(value: object) -> bool:
    """Whether a nested config value contains an Apex loop command."""

    if isinstance(value, dict):
        for key, item in value.items():
            if key == "command" and isinstance(item, str) and "apex_loop.py" in item:
                return True
            if is_apex_hook_entry(item):
                return True
    if isinstance(value, list):
        return any(is_apex_hook_entry(item) for item in value)
    return False


def cleanup_legacy_file(planned: PlannedCleanup) -> CleanupDecision:
    """Return cleanup decision for one legacy project-local hook file."""

    if not planned.path.exists():
        return CleanupDecision("absent")
    if planned.cleanup_type == "host-config":
        return cleanup_legacy_host_config(planned.path)
    if planned.cleanup_type == "runtime":
        return cleanup_legacy_runtime(planned.path)
    return CleanupDecision("skip-existing")


def cleanup_legacy_host_config(path: Path) -> CleanupDecision:
    """Strip Apex-managed hook entries from a legacy project-local host config."""

    if path.suffix == ".toml":
        return cleanup_toml_host_config(path)

    existing_content = path.read_text(encoding="utf-8", errors="ignore")
    try:
        existing = json.loads(existing_content)
    except json.JSONDecodeError:
        return CleanupDecision("skip-existing")
    if not isinstance(existing, dict):
        return CleanupDecision("skip-existing")

    cleaned = {
        key: value
        for key, value in existing.items()
        if key not in {"_generated_by", "_generated_marker"}
    }
    marker_removed = len(cleaned) != len(existing)
    hooks = cleaned.get("hooks")
    if not isinstance(hooks, dict):
        if marker_removed and not cleaned:
            return CleanupDecision("remove-legacy")
        if marker_removed:
            return CleanupDecision("strip-legacy", json.dumps(cleaned, ensure_ascii=False, indent=2) + "\n")
        return CleanupDecision("unchanged")

    removed = False
    clean_hooks: dict[str, list[object]] = {}
    for event, entries in hooks.items():
        if not isinstance(entries, list):
            continue
        kept_entries: list[object] = []
        for entry in entries:
            removed = removed or is_apex_hook_entry(entry)
            stripped = strip_apex_hook_entry(entry)
            if stripped is not None:
                kept_entries.append(stripped)
        if kept_entries:
            clean_hooks[str(event)] = kept_entries

    if not removed and not marker_removed:
        return CleanupDecision("unchanged")
    if clean_hooks:
        cleaned["hooks"] = clean_hooks
    else:
        cleaned.pop("hooks", None)
    if not cleaned:
        return CleanupDecision("remove-legacy")
    return CleanupDecision("strip-legacy", json.dumps(cleaned, ensure_ascii=False, indent=2) + "\n")


def cleanup_toml_host_config(path: Path) -> CleanupDecision:
    """Strip Apex-managed TOML hook block from a host config."""

    existing = path.read_text(encoding="utf-8", errors="ignore")
    stripped, changed = strip_apex_toml_block(existing)
    if not changed:
        return CleanupDecision("unchanged")
    if not stripped.strip():
        return CleanupDecision("remove-legacy")
    return CleanupDecision("strip-legacy", stripped)


def cleanup_legacy_runtime(path: Path) -> CleanupDecision:
    """Remove a generated project-local runtime copy."""

    existing = path.read_text(encoding="utf-8", errors="ignore")
    if GENERATED_MARKER in existing or "ApexPowers apex-init-project-hooks" in existing:
        return CleanupDecision("remove-legacy")
    return CleanupDecision("skip-existing")


def manifest_paths(root: Path, codex_home: Path, claude_home: Path, hook_scope: str) -> list[Path]:
    """Manifest files that can prove Apex ownership."""

    codex_base = root / ".codex" if hook_scope == "project" else codex_home
    claude_base = root / ".claude" if hook_scope == "project" else claude_home
    candidates = [
        resolve_inside(root, PROJECT_MANIFEST_PATH, "project-manifest"),
        resolve_inside(codex_base, HOST_MANIFEST_PATH, "codex-manifest"),
        resolve_inside(claude_base, HOST_MANIFEST_PATH, "claude-manifest"),
    ]
    output: list[Path] = []
    seen: set[str] = set()
    for path in candidates:
        key = path.resolve().as_posix().lower()
        if key not in seen:
            seen.add(key)
            output.append(path)
    return output


def base_for_manifest_root(root: Path, codex_home: Path, claude_home: Path, manifest_root: str) -> Path:
    """Base directory associated with a manifest root label."""

    if manifest_root == "codex":
        return codex_home
    if manifest_root == "claude":
        return claude_home
    return root


def manifest_relative_path(path: Path, base: Path) -> str:
    """Path relative to a manifest root when possible."""

    try:
        return path.resolve().relative_to(base.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def manifest_entry_for(
    planned: PlannedWrite,
    resolved_content: str,
    root: Path,
    codex_home: Path,
    claude_home: Path,
    write: bool,
) -> ManifestEntry:
    """Build a manifest entry from an install decision."""

    base = base_for_manifest_root(root, codex_home, claude_home, planned.manifest_root)
    current_hash = file_content_hash(planned.path) if write and planned.path.exists() else content_hash(resolved_content)
    return ManifestEntry(
        path=planned.path.resolve(),
        root=planned.manifest_root,
        relative_path=manifest_relative_path(planned.path, base),
        kind=planned.managed_kind,
        content_hash=current_hash,
        protected=planned.protected,
    )


def manifest_payload(
    root: Path,
    codex_home: Path,
    claude_home: Path,
    hook_scope: str,
    codex_config_format: str,
    entries: list[ManifestEntry],
) -> dict[str, Any]:
    """Machine-readable ownership payload shared by project and host manifests."""

    return {
        "version": MANIFEST_VERSION,
        "managed_by": GENERATED_MARKER,
        "hook_scope": hook_scope,
        "codex_config_format": codex_config_format,
        "project_root": root.resolve().as_posix(),
        "codex_home": codex_home.resolve().as_posix(),
        "claude_home": claude_home.resolve().as_posix(),
        "files": [
            {
                "path": entry.path.as_posix(),
                "root": entry.root,
                "relative_path": entry.relative_path,
                "kind": entry.kind,
                "hash": entry.content_hash,
                "protected": entry.protected,
            }
            for entry in sorted(entries, key=lambda item: (item.root, item.relative_path, item.kind))
        ],
    }


def write_or_preview_manifests(
    root: Path,
    codex_home: Path,
    claude_home: Path,
    hook_scope: str,
    codex_config_format: str,
    entries: list[ManifestEntry],
    write: bool,
) -> list[PlanResult]:
    """Write or preview all manifest files."""

    payload = manifest_payload(root, codex_home, claude_home, hook_scope, codex_config_format, entries)
    content = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    results: list[PlanResult] = []
    for path in manifest_paths(root, codex_home, claude_home, hook_scope):
        action = manifest_write_action(path, content)
        if write:
            path.parent.mkdir(parents=True, exist_ok=True)
            if action in {"create", "update"}:
                path.write_text(content, encoding="utf-8", newline="\n")
        results.append(PlanResult(path, action, "manifest"))
    return results


def manifest_write_action(path: Path, content: str) -> str:
    """Write action for a manifest file."""

    if not path.exists():
        return "create"
    existing = path.read_text(encoding="utf-8", errors="ignore")
    return "unchanged" if normalize_text(existing) == normalize_text(content) else "update"


def load_manifest_records(paths: list[Path], root: Path, codex_home: Path, claude_home: Path) -> list[ManifestRecord]:
    """Load manifest records from candidate manifest files."""

    records: list[ManifestRecord] = []
    seen: set[str] = set()
    for manifest_path in paths:
        if not manifest_path.is_file():
            continue
        try:
            payload = json.loads(manifest_path.read_text(encoding="utf-8", errors="ignore"))
        except json.JSONDecodeError:
            continue
        if not isinstance(payload, dict) or payload.get("managed_by") != GENERATED_MARKER:
            continue
        files = payload.get("files")
        if not isinstance(files, list):
            continue
        for item in files:
            entry = manifest_entry_from_payload(item, root, codex_home, claude_home)
            if not entry:
                continue
            key = entry.path.as_posix().lower()
            if key in seen:
                continue
            seen.add(key)
            records.append(ManifestRecord(entry, manifest_path))
    return records


def manifest_entry_from_payload(value: object, root: Path, codex_home: Path, claude_home: Path) -> ManifestEntry | None:
    """Parse one manifest entry with strict field validation."""

    if not isinstance(value, dict):
        return None
    path_value = value.get("path")
    root_value = value.get("root")
    relative_value = value.get("relative_path")
    kind_value = value.get("kind")
    hash_value = value.get("hash")
    if not all(isinstance(item, str) and item for item in (path_value, root_value, relative_value, kind_value, hash_value)):
        return None
    current_path = current_manifest_entry_path(path_value, root_value, relative_value, root, codex_home, claude_home)
    return ManifestEntry(
        path=current_path,
        root=root_value,
        relative_path=relative_value,
        kind=kind_value,
        content_hash=hash_value,
        protected=bool(value.get("protected", False)),
    )


def current_manifest_entry_path(path_value: str, root_value: str, relative_value: str, root: Path, codex_home: Path, claude_home: Path) -> Path:
    """Current path for a manifest entry, preferring root-relative ownership data."""

    if root_value in {"project", "codex", "claude"}:
        base = base_for_manifest_root(root, codex_home, claude_home, root_value)
        relative_path = Path(relative_value)
        if not relative_path.is_absolute():
            return (base / relative_path).resolve()
    return Path(path_value).expanduser().resolve()


def is_allowed_uninstall_path(path: Path, roots: list[Path]) -> bool:
    """Whether manifest entry is inside an expected project or agent root."""

    resolved = path.resolve()
    for root in roots:
        try:
            resolved.relative_to(root.resolve())
            return True
        except ValueError:
            continue
    return False


def uninstall_decision(record: ManifestRecord, force: bool, allowed_roots: list[Path]) -> UninstallDecision:
    """Return uninstall action for one loaded manifest record."""

    entry = record.entry
    if not is_allowed_uninstall_path(entry.path, allowed_roots):
        return UninstallDecision("skip-outside-root")
    if entry.protected:
        return UninstallDecision("skip-protected")
    if not entry.path.exists():
        return UninstallDecision("absent")
    if entry.kind == "host-config":
        cleanup = cleanup_legacy_host_config(entry.path)
        action = {
            "strip-legacy": "scrub-managed",
            "remove-legacy": "remove-managed",
            "unchanged": "unchanged",
            "skip-existing": "skip-existing",
        }.get(cleanup.action, cleanup.action)
        return UninstallDecision(action, cleanup.content)

    existing = entry.path.read_text(encoding="utf-8", errors="ignore")
    current_hash = content_hash(existing)
    if force or current_hash == entry.content_hash or GENERATED_MARKER in existing or "ApexPowers apex-init-project-hooks" in existing:
        return UninstallDecision("remove-managed")
    return UninstallDecision("skip-modified")


def apply_uninstall_plan(
    root: Path,
    codex_home: Path,
    claude_home: Path,
    hook_scope: str,
    write: bool,
    force: bool,
) -> list[PlanResult]:
    """Apply or preview manifest-scoped uninstall actions."""

    manifests = manifest_paths(root, codex_home, claude_home, hook_scope)
    records = load_manifest_records(manifests, root, codex_home, claude_home)
    allowed_roots = [root, codex_home, claude_home]
    results: list[PlanResult] = []
    incomplete = False
    for record in sorted(records, key=lambda item: item.entry.path.as_posix()):
        decision = uninstall_decision(record, force, allowed_roots)
        if write and decision.action == "scrub-managed" and decision.content is not None:
            record.entry.path.write_text(decision.content, encoding="utf-8", newline="\n")
        elif write and decision.action == "remove-managed":
            record.entry.path.unlink()
        if decision.action in {"skip-modified", "skip-existing", "skip-outside-root"}:
            incomplete = True
        results.append(PlanResult(record.entry.path, decision.action, record.entry.kind))

    for manifest_path in manifests:
        action = uninstall_manifest_action(manifest_path, force, complete=not incomplete)
        if write and action == "remove-manifest":
            manifest_path.unlink()
        results.append(PlanResult(manifest_path, action, "manifest"))
    return results


def uninstall_manifest_action(path: Path, force: bool, complete: bool) -> str:
    """Uninstall action for an Apex manifest file."""

    if not path.exists():
        return "absent"
    if not complete:
        return "keep-manifest"
    if force:
        return "remove-manifest"
    try:
        payload = json.loads(path.read_text(encoding="utf-8", errors="ignore"))
    except json.JSONDecodeError:
        return "skip-existing"
    if isinstance(payload, dict) and payload.get("managed_by") == GENERATED_MARKER:
        return "remove-manifest"
    return "skip-existing"


def apply_plan(
    root: Path,
    codex_home: Path,
    claude_home: Path,
    hook_scope: str,
    codex_config_format: str,
    directories: list[PlannedDirectory],
    files: list[PlannedWrite],
    cleanups: list[PlannedCleanup],
    write: bool,
    force: bool,
) -> list[PlanResult]:
    """Apply or preview the installation plan."""

    results: list[PlanResult] = []
    manifest_entries: list[ManifestEntry] = []
    for directory in directories:
        if write:
            directory.path.mkdir(parents=True, exist_ok=True)
        action = "exists" if directory.path.exists() else "create"
        results.append(PlanResult(directory.path, action, "directory"))

    for planned in files:
        decision = should_write(planned, force)
        if write and decision.should_write:
            planned.path.parent.mkdir(parents=True, exist_ok=True)
            planned.path.write_text(decision.content, encoding="utf-8", newline="\n")
        results.append(PlanResult(planned.path, decision.action, "file"))
        if planned.track_manifest and decision.action not in {"skip-existing"}:
            manifest_entries.append(manifest_entry_for(planned, decision.content, root, codex_home, claude_home, write))

    for planned in cleanups:
        decision = cleanup_legacy_file(planned)
        if write and decision.action == "strip-legacy" and decision.content is not None:
            planned.path.write_text(decision.content, encoding="utf-8", newline="\n")
        elif write and decision.action == "remove-legacy":
            planned.path.unlink()
        results.append(PlanResult(planned.path, decision.action, "legacy"))
    results.extend(write_or_preview_manifests(root, codex_home, claude_home, hook_scope, codex_config_format, manifest_entries, write))
    return results


def print_text_results(root: Path, results: list[PlanResult], write: bool) -> None:
    """Render human-readable results."""

    mode = "WRITE" if write else "DRY-RUN"
    for result in results:
        print(f"{mode} {result.kind} {result.action}: {source_relative_path(result.path, root)}")
    print(f"Summary: {len(results)} hook targets checked.")


def print_json_results(
    root: Path,
    codex_home: Path,
    claude_home: Path,
    hook_scope: str,
    codex_config_format: str,
    operation: str,
    results: list[PlanResult],
    write: bool,
) -> None:
    """Render JSON results."""

    payload = {
        "root": str(root),
        "hook_scope": hook_scope,
        "codex_config_format": codex_config_format,
        "operation": operation,
        "codex_home": str(codex_home),
        "claude_home": str(claude_home),
        "write": write,
        "results": [
            {
                "path": source_relative_path(result.path, root),
                "kind": result.kind,
                "action": result.action,
            }
            for result in results
        ],
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))


def main() -> int:
    """CLI entrypoint."""

    args = parse_args()
    root = Path(args.root).expanduser().resolve()
    if not root.is_dir():
        raise SystemExit(f"Project root is not a directory: {root}")

    codex_home = resolve_base(args.codex_home, get_agent_home("codex"))
    claude_home = resolve_base(args.claude_home, get_agent_home("claude"))
    codex_config_format = resolve_codex_config_format(codex_home, args.hook_scope, args.codex_config_format)
    operation = "uninstall" if args.uninstall else "update" if args.update else "install"
    if args.uninstall:
        results = apply_uninstall_plan(root, codex_home, claude_home, args.hook_scope, args.write, args.force)
    else:
        directories, files, cleanups = planned_outputs(root, codex_home, claude_home, args.hook_scope, codex_config_format)
        results = apply_plan(root, codex_home, claude_home, args.hook_scope, codex_config_format, directories, files, cleanups, args.write, args.force)
    if args.json:
        print_json_results(root, codex_home, claude_home, args.hook_scope, codex_config_format, operation, results, args.write)
    else:
        print_text_results(root, results, args.write)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
